### ISSUE TITLE
GameHelper incorrect signin state after signout from within Google Default UI

### ISSUE THREAD

**Issue by arberg** [playgameservices/android-basic-samples#121]
If signout is made from within Google Default UI (eg. click achievements, then settings, then signout) then the outer layers of the code thinks it is signed in, but the inner layers throws exception on pretty much any action except reconnectClient, because the inner layer knows that it is signed out.

So after signing out from within default ui:
- mGoogleApiClient.isConnected() returns true (and therefore BaseGameActivity+GameHelper.isSignedIn() returns true)
- GameHelper.signOut crashes (I think) with already signed out
- GameHelper.beginUserInitiatedSignIn does nothing because it thinks its already signed in
- Starting Intent to show Achievements or leaderboards throws SecurityException.

It seems the problem might be that mGoogleApiClient is left in a bad state, so I tried setting it to null, and running setup again creating a new object. That worked and I could do new login and show achievements and leaderboards, but once I exit the activity and start it again, a new signin is made to Google Apis, and then it crashes with bad channel or something. I guess this just shows that we (non-Googlers) shouldn't try to modify the GameHelper flow, because we don't know the secret rules of the underlying layer, but I guess that's fine.

What did work is catching the SecurityException from showAchievements and then do reconnect client, and from Listener.onSignInSucceeded do showAchievements again. It would be nice with some (Java)Doc telling me this was a usecase for reconnectClient. I'm not sure I have circumvented all problems by this approach, but I have not yet discovered any new crashes.

Best Alex

**Comment by samtstern** [comment]
@arberg I know it has been a while but I got an answer on this which is satisfying (and something I didn't actually know).  I'll copy it below:

"""
This is actually not a bug - it's working as intended.

When you start a GPGS activity, you have to start it with `startActivityForResult`. If the user clicks on sign-out, the `GoogleApiClient` is NOT disconnected - it's just in a "signed out" state. The `onActivityResult` here will return a status `RECONNECT_REQUIRED`. At this point, the developer should reconnect their client, and life goes on as expected.
"""

**Comment by arberg** [comment]
@samtstern Thank you for the feedback. It makes sense. Its not exactly easy on the developer, and I would hazard a guess that most would get that part wrong based on the current documentation and sample-library, but that's not my table. I appreciate the info. 
All the best, Alex

**Comment by samtstern** [comment]
You're certainly right that this is not easy on the developer.  Like I mentioned, I didn't even know this myself and writing the samples is my job.  I will try to document this appropriately.

**Comment by arberg** [comment]
Awesome, I appreciate the effort.

**Comment by MSDuarte** [comment]
Thanks for the help @samtstern!
