### ISSUE TITLE
Splitting Google Play Services makes GameUtils not compiling

### ISSUE THREAD

**Issue by cesards** [playgameservices/android-basic-samples#130]
I have stripped the Play Services, not to reach the 65k methods.

My `GameHelper` class doesn't compile because of the `import com.google.android.gms.appstate.AppStateManager` dependancy.

I am using the following Play Services
```java
// Google Play Services
compile "com.google.android.gms:play-services-plus:${PLAY_SERVICES_VERSION}"
compile "com.google.android.gms:play-services-identity:${PLAY_SERVICES_VERSION}"
compile "com.google.android.gms:play-services-location:${PLAY_SERVICES_VERSION}"
compile "com.google.android.gms:play-services-appindexing:${PLAY_SERVICES_VERSION}"
compile "com.google.android.gms:play-services-games:${PLAY_SERVICES_VERSION}"
compile "com.google.android.gms:play-services-base:${PLAY_SERVICES_VERSION}"
```

I cannot find wehre is localted `AppStateManager` in the separated services. Any help is appreciated!!

**Comment by cesards** [comment]
Ok solved, thanks to this [post](http://www.reddit.com/r/androiddev/comments/2oo44w/google_play_services_6587_released_split_modules/) I have discovered there is a lack of documentation in the official site: https://developer.android.com/google/play-services/setup.html#split

compile 'com.google.android.gms:play-services-appstate:6.5.87' was needed

**Comment by claywilkinson** [comment]
Thanks for the details @cesards. Appstate (aka CloudSave) is a deprecated API (see https://developers.google.com/games/services/android/savedgames).  Do you use it?  If you are looking to strip out methods, maybe removing all the references to AppStateManager would help towards that end?
