### ISSUE TITLE
BaseGameUtils now depends on the root build.gradle

### ISSUE THREAD

**Issue by dileeppg** [playgameservices/android-basic-samples#131]
@claywilkinson
With recent changes, it seems the BaseGameUtils module is unusable independently since the module build.gradle has properties such as 'android_appcompat_library' that are assigned in the root build.gradle.

I was trying to import BaseGameUtils module into my game project when I met the issue. Either this needs a revert or the 'Accessing the Games APIs' documentation (https://developers.google.com/games/services/android/init) probably needs an update.

**Comment by samtstern** [comment]
@dileeppg I have submitted a pull request to address this issue.

**Comment by dileeppg** [comment]
@samtstern @claywilkinson 

I just downloaded the latest zip and imported the BaseGameUtils module into a new project. But Gradle Project Sync failed.

Error:(15, 0) No such property: android_compile_version for class: org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler_Decorated

**Comment by dileeppg** [comment]
@samtstern @claywilkinson
When I load the entire project. It compiles without issues. The error is there only when BaseGameUtils module is imported separately.

**Comment by samtstern** [comment]
@dileeppg sorry about that!  I just put in a new fix.  I tried importing BaseGameUtils into a new project and everything resolves for me

**Comment by dileeppg** [comment]
@samtstern Cool! That was super quick turnaround.
