### ISSUE TITLE
Handle rotation in RealTime multiplayer game

### ISSUE THREAD

**Issue by djavan-bertrand** [playgameservices/android-basic-samples#136]
Hi, 

How would you handle the screen rotation (or other config changes) when playing a real time multiplayer game ?
In your example, you call leaveRoom in the onStop, so the player leave the game as soon as he rotate his screen.

Thanks in advance, 
Djavan

**Comment by claywilkinson** [comment]
Hi @djavan-bertrand, questions like this are pretty general, and not directly related to the samples.  I'd suggest searching and/or posting this type of question on stackoverflow: http://stackoverflow.com/questions/tagged/google-play-games.  It will reach a much wider audience.
