### ISSUE TITLE
Smart Lock / Trusted Places does not work in v7.0.99

### ISSUE THREAD

**Issue by mnpenner** [playgameservices/android-basic-samples#137]
I'm not quite sure if this is the correct place to post this issue, I got linked [from here](http://stackoverflow.com/a/27646542/65387). If this is incorrect, kindly redirect me to the appropriate issue tracker (please not another forum).

Smart Lock/Trusted Places never unlocks my phone with Google Play Services v7.0.99 on Nexus 4, Android 5.1. The issue appears to be specific to Play Services >= v7.0.97. Please see the following links for more details:

- https://code.google.com/p/android/issues/detail?id=167904&q=smart%20lock&colspec=ID%20Type%20Status%20Owner%20Summary%20Stars
- https://code.google.com/p/android/issues/detail?id=163150&q=smart%20lock&colspec=ID%20Type%20Status%20Owner%20Summary%20Stars
- https://code.google.com/p/android/issues/detail?id=162420&q=smart%20lock&colspec=ID%20Type%20Status%20Owner%20Summary%20Stars
- https://productforums.google.com/forum/m/#!category-topic/nexus/device-security/WlsJANn9eZ8
- http://forums.androidcentral.com/android-5-0-lollipop/499950-smart-lock-trusted-places-not-working-anymore.html
- https://productforums.google.com/forum/#!topic/nexus/tPFeEWmN1Jw%5B1-25%5D
- https://productforums.google.com/forum/#!topic/nexus/WlsJANn9eZ8%5B1-25%5D

There's probably a number of other reports as well, but I think that's enough. I've tried a number of the supposed "fixes" like removing my trusted places and re-adding them, but none of the tricks work.

**Comment by samtstern** [comment]
Hi @mnpenner,

This repository is just for the Play Game Services Android sample apps so I will close this issue.  However I will take your comment and report it internally to the Smart Lock team, thanks for bringing this to my attention!

- Sam
