### ISSUE TITLE
Is There a problem With Google Play Services?

### ISSUE THREAD

**Issue by simsis3d** [playgameservices/android-basic-samples#138]
I published my game 3 days ago, now there are more than 3.000 active players who uses Real Time Multiplayer. Today, nobody is able to create quick game! Playing with friends with invitations is okay but quick game is not working right now! Is there a problem with Google? Is anybody experiencing this also? What should I do? How can I connect with Google?

**Comment by thomasdc** [comment]
I'm experiencing exactly the same problem!

**Comment by samtstern** [comment]
This is a known issue right now.  It is affecting a small percentage of users.  The fix is already in place and should be rolling out soon.  If you can reproduce this tomorrow please re-open this thread.
