### ISSUE TITLE
Internal data leak within a DataBuffer object detected!

### ISSUE THREAD

**Issue by newandroid66** [playgameservices/android-basic-samples#142]
Hi.

I've got a log as below that about crash from gms module with chromium.
Please FIX it for entire world.
No one got a solution. but google who do nothing so far.
-----------------------------------------
05-06 11:59:21.347: W/art(2537): Attempt to remove local handle scope entry from IRT, ignoring
05-06 11:59:21.365: W/google-breakpad(18883): -----BEGIN BREAKPAD MICRODUMP-----
05-06 11:59:21.365: W/google-breakpad(18883): O A arm 04 armv7l 3.4.0-g8a80a0e #1 SMP PREEMPT Thu Feb 5 04:14:26 UTC 2015
05-06 11:59:21.373: W/google-breakpad(18883): S 0 9F712B30 9F712000 00001000
05-06 11:59:21.378: W/google-breakpad(18883): S 9F712000 000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
05-06 11:59:21.378: W/google-breakpad(18883): S 9F712180 000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
05-06 11:59:21.379: W/google-breakpad(18883): S 9F712300 000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
05-06 11:59:21.379: W/google-breakpad(18883): S 9F712480 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000401211115D3B63A500000000104001A200000000000000000000000000000000000000000000000000000000000000000000000000000000
05-06 11:59:21.379: W/google-breakpad(18883): S 9F712600 00000000000000000000000000000000000000000000B09E100000009180B09E9180B09E6004B09E01000000B98E0055104001A20000909E616A919E104001A201000000DB4F63A5149F2CA6001BB09E400000000027719FAC0B909E000000010027719F010000000026719F2806909E010000006827719F6181A09E6827719F4112939E0000909EC1A8919E104001A201000000DB4F63A5104001A26004B09E302659A680E858A6A00D909EE026719F00000000000000000000000000000000E026719F548501A2593362A589865EA5A180B09EA828719F000000006DD768A5004001A2302659A6E026719F004001A200000000000000000000000000000000782559A6E026719F004001A200000000000000000000000000000000F82559A6E026719F004001A200000000000000000000000000000000B02659A6E026719F004001A200000000000000000000000000000000B02559A6E026719F004001A200000000000000000000000000000000082559A6E026719F908201A2104001A2
05-06 11:59:21.379: W/google-breakpad(18883): S 9F712780 AC27719FA00FFFFF088301A273B963A503000000C0EE12A20000B09EE8EE12A20083AFB4000000552883AFB4F85351A60000000000000000104001A2088301A200000000C9D161A501000000004001A260D2000000000000A9800055094C62A5682659A6A00FFFFF8483AFB4780B0055C8020000C8020000688D62A600000055000000000100005800000000B98201A2A88201A20064015504000000100000001A0000001E000000BD6B4955A96C0C00BD6B4955E84801A2A88201A2F9C679A5E84801A2A88201A2A828719F0000008001000000039E62A5A828719FA00FFFFF0000005500000055A00FFFFF000000550000005500000000010000005D8462A5E8931DA21A0265A6000000000000000004F112A22883AFB4D835909E2883AFB40000000000000000102E59A6104001A2705451A6A88201A201000000688D62A664000000640000000000000064000000FFFFFF7F6500000064000000280000002300000002000000004001A2C72150A5F8FFFFFF02000000F012B6B4C14CC9A5
05-06 11:59:21.379: W/google-breakpad(18883): S 9F712900 004001A200000000A0EF12A20B000000E0951DA26FB3DBA5BD6B4955ED6C0C00BD6B4955A88201A200000000FFFFFFFFE84801A200004000FFFFFFFF00000000000000000000000032000000000000000000000000000000FFFFFF7F0100000000000000CC8501A265000000E703000000000000E7030000FFFFFF7F2C040000E703000000000000810000008CFC2B9E0000000000000000010000008CFC2B9E2C9665A601000000B82D719F00000000810000008C69B0B40000000000000000B82D719F0000000081000000ACCB0EA200000000000000003200000000000000E80300000000000032000000000000000000000003000000E8030000A88201A2988301A20920431520D105A248D90EA2010000000000000048D90EA201000000BD80D3A420D105A20100000085B55BA501000000B9B65BA56E44C7E6096E9948F100000067BFD5A4104001A2F10000000000000078EB88B4E4951DA257DCD1A4744100007140F62A982A719F802A719F01000000F8951DA2982A719F29DDD1A4
05-06 11:59:21.382: W/google-breakpad(18883): S 9F712A80 982A719FF82A719FF8B11C02594EF1A5982A719F03000000D40FE7B6CF48F1A55C000000010000005C000000010000005C00000001000000F02A719F08000000DCEB88B4F00F03A2DCEB88B40C2B719F38E419A200000000D40FE7B6E02B719F94A403A2F00F03A2202B719F1725D3A494A403A20920431500000000000000006061B0B46061B0B4947106A200150FA200000000C1D5D5A4D82B719FE02B719F00000000882C719F482B719FF02B719F01000000482B719FC09A09A21B4447A5EC7A29A600000000806D09A2873D47A5802C719F802C719FD0E323A2F33A15A500A10AA2E74047A500000000802C719FF82B719FFB09D2A4C000C0B4040000406061B0B40000000041B6C6E603000000F0941DA20129D5A4083A47A6257926A681040000047B29A6E4010000047B29A6CCED12A2F0941DA2CCED12A2345000FFD40FE7B6000000000000000010BBC9AEF467B3B457DCD1A403000000382C719F1D4E47A50800000000000000A80503A2B4ED12A2342C719F0000000000000000
05-06 11:59:21.382: W/google-breakpad(18883): S 9F712C00 00150FA200000000042D719F0000000001000000A80503A2080E03A2A80503A2482C719F00ED12A2482C719F802C719F01000000902C719F882C719F0CED12A2B02D719F3130D3A4A80503A2B4ED12A202000000FFFFFFFFD09E03A2802C719F00ED12A2C935D3A400000000D09E03A200ED12A2802C719F982C719F613DD3A4902D13A2000000000000000000000000D0E323A2DB3A15A5C4F33CA6FBE01EA67F0000001D4E47A5E6010000010000000000000000ED12A2F944C7E603000000D82713A2E82713A2FB9203A27F46D3A4F944C7E603000000724B1C0200000000042D719F282D719F042D719FC0BAB9B41B00000094ED12A2E09203A211D5D3A400C0D2AE000000000000000000150FA20000000000000000C0BAB9B4A0C10EA200ED12A2392DD3A400ED12A200000000010000000100010000000000282D719FA0C10EA26700D5A4682104A2682104A2807911A2A0C10EA2C0BAB9B4807911A2887911A2887911A2911BE1B6ADD3D4A4807911A2C43D00000000000000D0AEAE
05-06 11:59:21.382: W/google-breakpad(18883): S 9F712D80 00000000807911A2C07911A2807911A278000000B11BE1B6911BE1B6887911A2911BE1B6F5FAE0B6B02D719F00000000B02D719F807911A216000000000000000000000009204315000000000000000000000000000000000000000000000000C02713A2300A03A2200A03A2280A03A2000000000000000000000000009C0DA2000000000000000000000000C01B0FA2000000000000000000980DA200000000000000000000000000000000700B03A2B00B03A2580C03A2004001A20100000028A6B7B40000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
05-06 11:59:21.382: W/google-breakpad(18883): S 9F712F00 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
05-06 11:59:21.382: W/google-breakpad(18883): C 06000040000009A2000000000000000000000000680E03A200000000BC4F63A6403E63A600000000E02B719FE82B719FEC7A29A628DD61A6302B719F1B4447A5C45719A530000E600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
05-06 11:59:21.383: W/google-breakpad(18883): M B6F96000 00000000 00003000 A417B9A61EDF19D1CF6F3BFB065924FD0 app_process32
05-06 11:59:21.383: W/google-breakpad(18883): M A0529000 00000000 0046A000 D02BDFC606B58B510E2C89ACD619629E0 libsc-a3xx.so
05-06 11:59:21.383: W/google-breakpad(18883): M A2402000 00000000 00009000 915DE16282C89571172C01EB431AF9F10 eglsubAndroid.so
05-06 11:59:21.383: W/google-breakpad(18883): M A2AEF000 00000000 00006000 21DA574FDFC3D5E1A625A092D9089D8A0 libqdutils.so
05-06 11:59:21.383: W/google-breakpad(18883): M A2AF5000 00000000 00005000 B25F6918FD9BDCF73E98107264AC42390 libmemalloc.so
05-06 11:59:21.383: W/google-breakpad(18883): M A2AFA000 00000000 00005000 95BECBB2CBF862DCD1A38EAB9D07CED20 gralloc.msm8974.so
05-06 11:59:21.390: W/google-breakpad(18883): M A2C36000 00000000 002F0000 A6960F16C60FB726CCB06A0C369A15540 libMNDictionaryEngineKor.so
05-06 11:59:21.391: W/google-breakpad(18883): M A303D000 00000000 00005000 1950F9D74048391E963DD5F28EDAA7140 libMNSecEngine.so
05-06 11:59:21.391: W/google-breakpad(18883): M A4A79000 00000000 01A66000 02ED9811FCF64CCF917969B967D6C4D90 libwebviewchromium.so
05-06 11:59:21.392: W/google-breakpad(18883): M AAE79000 00000000 00003000 92AEC9935A8E5A07D59E3868060A5F2E0 libwebviewchromium_loader.so
05-06 11:59:21.392: W/google-breakpad(18883): M AAE7C000 00000000 00003000 8FF5949AE957364C270D0F448DAD4FE20 libjnigraphics.so
05-06 11:59:21.393: W/google-breakpad(18883): M AAE7F000 00000000 00008000 F2B1298EE4C6EA0900CDACD17FB5C16B0 libcompiler_rt.so
05-06 11:59:21.394: W/google-breakpad(18883): M AAE87000 00000000 00010000 E2C6CBE7D4588EF8111B01903B27FEA80 libandroid.so
05-06 11:59:21.398: W/google-breakpad(18883): M AAE97000 00000000 00142000 C28729A3F5B9E8321F3A31FB4585FDC20 libGLESv2_adreno.so
05-06 11:59:21.401: W/google-breakpad(18883): M AAFDA000 00000000 00034000 8832F70AF78F96C568BC5D206A3D8DFD0 libGLESv1_CM_adreno.so
05-06 11:59:21.402: W/google-breakpad(18883): M AB00E000 00000000 00035000 3F4962E5CA39C006C3EE7AE5FFBF61530 libgsl.so
05-06 11:59:21.403: W/google-breakpad(18883): M AB043000 00000000 00004000 40F9D5367F3F96608023D8B450A243250 libadreno_utils.so
05-06 11:59:21.403: W/google-breakpad(18883): M AB049000 00000000 00029000 D7DEE555A5420274729B2A3AF0369A160 libEGL_adreno.so
05-06 11:59:21.404: W/google-breakpad(18883): M AB9DF000 00000000 00018000 41561A97B1EE9DD7478395AC81CA83C20 libjavacrypto.so
05-06 11:59:21.405: W/google-breakpad(18883): M AB9F7000 00000000 00009000 8452CE587CC6C1496722726A3DA08AD80 librs_jni.so
05-06 11:59:21.405: W/google-breakpad(18883): M ABA00000 00000000 00006000 1144525A072A9E8FC369E7AC816948A10 libaudioeffect_jni.so
05-06 11:59:21.406: W/google-breakpad(18883): M ABA06000 00000000 00004000 CDA9BA072D4DECC71C5E63467275E7EE0 libsoundpool.so
05-06 11:59:21.406: W/google-breakpad(18883): M ABA0A000 00000000 0001B000 F59669C665FE4B073886A8DAAECEA86F0 libvorbisidec.so
05-06 11:59:21.407: W/google-breakpad(18883): M ABA25000 00000000 00022000 C2E87E6EB6315B42B05C2BD601B418820 libstagefright_omx.so
05-06 11:59:21.407: W/google-breakpad(18883): M ABA47000 00000000 00007000 741CC494F5299870A1C62FD71E37AE5F0 libstagefright_avc_common.so
05-06 11:59:21.410: W/google-breakpad(18883): M ABA4E000 00000000 0003C000 F19A7DFF3B6F3AF94EAE23CA11905BAD0 libopus.so
05-06 11:59:21.411: W/google-breakpad(18883): M ABA8A000 00000000 0001B000 87AFCC5E47ED503148F1AA03777E88590 libdrmframework.so
05-06 11:59:21.412: W/google-breakpad(18883): M ABAA5000 00000000 0000E000 D02CB251CF8787A770DE2CFDC52A2B040 libstagefright_amrnb_common.so
05-06 11:59:21.413: W/google-breakpad(18883): M ABAB3000 00000000 00115000 E75956B9C65EADF3A05E323BECEF1FD50 libstagefright.so
05-06 11:59:21.413: W/google-breakpad(18883): M ABBC8000 00000000 00016000 A2D19830A4461800EBFEC5FFFEB343B90 libmtp.so
05-06 11:59:21.415: W/google-breakpad(18883): M ABBDE000 00000000 0002C000 556D915BB9DB458CDEF0D8E5271D8DCE0 libexif.so
05-06 11:59:21.416: W/google-breakpad(18883): M ABC0A000 00000000 0003D000 B0E6763FD465F3CD48CAEBCB48DB950D0 libmedia_jni.so
05-06 11:59:21.416: W/google-breakpad(18883): M AE9EC000 00000000 00003000 F36630BD0C6DC4B52A0E5D5D57BE682A0 memtrack.msm8974.so
05-06 11:59:21.421: W/google-breakpad(18883): M AEB52000 00000000 0008C000 FB561B1AA2DB1D71AA82CA0C0F01EAFB0 libMNKeyboardLayoutInflator.so
05-06 11:59:21.422: W/google-breakpad(18883): M AF002000 00000000 00004000 9FC00D0B150FE9FC57763A76206D1D550 libstagefright_yuv.so
05-06 11:59:21.422: W/google-breakpad(18883): M AF122000 00000000 00004000 F007D0E8B4B1447628068777E701EBBC0 libwebviewchromium_plat_support.so
05-06 11:59:21.423: W/google-breakpad(18883): M B05D2000 00000000 00038000 FE4EB356A2DF9D6013F3C471876ED1C20 libjavacore.so
05-06 11:59:21.428: W/google-breakpad(18883): M B3530000 00000000 0003C000 1DF2F40B7D3252F0300CD36A4746DB9C0 libMNHelpersEx.so
05-06 11:59:21.429: W/google-breakpad(18883): M B356E000 00000000 00028000 FE90757EE155F5DD712A45AFB4348F0F0 libMNLogInKeyboardEngine.so
05-06 11:59:21.432: W/google-breakpad(18883): M B359A000 00000000 0001A000 4052E675D57BFF2B5C0BEBFF5BEB7A250 libMNNativeHelper.so
05-06 11:59:21.433: W/google-breakpad(18883): M B44F5000 00000000 00307000 AAA0F066B968C8E97CFAABA3AB9DD7520 libart.so
05-06 11:59:21.434: W/google-breakpad(18883): M B5002000 00000000 00003000 E11DA546CE9E08D1D647E8E1135DAD810 libstagefright_enc_common.so
05-06 11:59:21.434: W/google-breakpad(18883): M B5007000 00000000 0000B000 D2AB743CCCD8D2EB9B66A47707CC1E530 libjhead.so
05-06 11:59:21.435: W/google-breakpad(18883): M B523F000 00000000 00003000 133BEE27C6351072BEF5780E5368857F0 libsigchain.so
05-06 11:59:21.435: W/google-breakpad(18883): M B5244000 00000000 00009000 E117445193BF46AD0E4CBBC6DB5F76E10 libbacktrace_libc++.so
05-06 11:59:21.435: W/google-breakpad(18883): M B526D000 00000000 00005000 D3EA22EB9F383751AB500AE5951F0DB30 libpowermanager.so
05-06 11:59:21.436: W/google-breakpad(18883): M B5272000 00000000 0000F000 E43E7FA869E4BCDAA3CC9601DF5A6A520 libcommon_time_client.so
05-06 11:59:21.436: W/google-breakpad(18883): M B5281000 00000000 0003D000 6CD267BECE448A66778527D376FF0F720 libbcinfo.so
05-06 11:59:21.436: W/google-breakpad(18883): M B52BE000 00000000 00024000 461206238C83FB507F268B026584DA8B0 libbcc.so
05-06 11:59:21.436: W/google-breakpad(18883): M B5302000 00000000 00938000 AEF791EAC2FA5494FB743231421483160 libLLVM.so
05-06 11:59:21.436: W/google-breakpad(18883): M B5C41000 00000000 00004000 7AE0C00FAEDEA3E81109CC784D49A6960 libunwind-ptrace.so
05-06 11:59:21.437: W/google-breakpad(18883): M B5C45000 00000000 0000E000 FEC52DCEA9703BC3D04786B7558687FF0 libunwind.so
05-06 11:59:21.438: W/google-breakpad(18883): M B5C99000 00000000 00007000 3874D35A672DF92604963290963F44990 libgccdemangle.so
05-06 11:59:21.439: W/google-breakpad(18883): M B5CA0000 00000000 00012000 1ED721809D4ADEC8823197FA7B47EA470 libpcre.so
05-06 11:59:21.439: W/google-breakpad(18883): M B5CB2000 00000000 00094000 E1512A4C80BFFB98EE1A27F8109CA7CE0 libc++.so
05-06 11:59:21.439: W/google-breakpad(18883): M B5D49000 00000000 00028000 A375B97071FE90C7E0F811F67EB42A5D0 libpng.so
05-06 11:59:21.440: W/google-breakpad(18883): M B5D71000 00000000 0005A000 659F1470013A04F7702E4BAB65F034E70 libft2.so
05-06 11:59:21.440: W/google-breakpad(18883): M B5DCB000 00000000 00017000 6277772E2C87892DB67F815EBEBEBD810 libstagefright_foundation.so
05-06 11:59:21.440: W/google-breakpad(18883): M B5DE2000 00000000 0000A000 C84019C90BCA7E95A773B5A75A460D880 libnbaio.so
05-06 11:59:21.441: W/google-breakpad(18883): M B5DEC000 00000000 00006000 F4F99E4A6E63BF8C8005D96B2BAC8CEB0 libgabi++.so
05-06 11:59:21.441: W/google-breakpad(18883): M B5DF2000 00000000 0001D000 7176C4FDA0EED9424034523F8CA475C80 libRScpp.so
05-06 11:59:21.441: W/google-breakpad(18883): M B5E0F000 00000000 0003A000 07D4EC10ADCE242DB2DCB033EC3630920 libRS.so
05-06 11:59:21.441: W/google-breakpad(18883): M B5E49000 00000000 00005000 254351EC49125FE3A72F78EAB38381410 libwpa_client.so
05-06 11:59:21.442: W/google-breakpad(18883): M B5E4E000 00000000 00003000 2D9083CB8C22C02E1412DA13B1CA43AE0 libsync.so
05-06 11:59:21.442: W/google-breakpad(18883): M B5E51000 00000000 00006000 AC1D054A26491BE96E8BCCB1E5F2926F0 libspeexresampler.so
05-06 11:59:21.444: W/google-breakpad(18883): M B5E57000 00000000 00071000 A12BAF7D82BE28EC681730452D351E880 libGLES_trace.so
05-06 11:59:21.445: W/google-breakpad(18883): M B5EC8000 00000000 00009000 BBF745C99E586EA55F33C880C56C60100 libbacktrace.so
05-06 11:59:21.446: W/google-breakpad(18883): M B5ED2000 00000000 0001A000 03AD92B0BEDAA751C0016E97AE374CAE0 libz.so
05-06 11:59:21.446: W/google-breakpad(18883): M B5EEC000 00000000 00004000 3CBDF0DE27B9554508AD60FDC96CBC620 libusbhost.so
05-06 11:59:21.446: W/google-breakpad(18883): M B5EF0000 00000000 0000C000 4C7E06828A3225C3FD4003E47756B8730 libui.so
05-06 11:59:21.448: W/google-breakpad(18883): M B5EFC000 00000000 0003B000 2FE003E5119C67BABE1A9FAB459A5A5D0 libstlport.so
05-06 11:59:21.449: W/google-breakpad(18883): M B5F37000 00000000 00041000 127BC979BDE074D327028354657BA61B0 libssl.so
05-06 11:59:21.449: W/google-breakpad(18883): M B5F78000 00000000 0005F000 D02DDA4D9C353EF3E6279A1E1789C4250 libsqlite.so
05-06 11:59:21.449: W/google-breakpad(18883): M B5FD8000 00000000 0000F000 F954BA248E12C9AF32F54434F977FEF80 libsoundtrigger.so
05-06 11:59:21.450: I/GLSUser(2846): [GLSUser] getAuthtoken(<ELLIDED:28420>, oauth2:https://www.googleapis.com/auth/drive.appdata https://www.googleapis.com/auth/drive https://www.googleapis.com/auth/drive.apps) -> status: null)
05-06 11:59:21.450: I/GLSUser(2846): [GLSUser] Extracting token using key: Auth
05-06 11:59:21.450: W/google-breakpad(18883): M B5FE7000 00000000 00051000 6E42AB0836D73C21533C08A98EE7B24C0 libsonivox.so
05-06 11:59:21.451: W/google-breakpad(18883): M B603D000 00000000 0022F000 6466AA6996ABB20C8FE9BE6C8E5D0EC40 libskia.so
05-06 11:59:21.452: W/google-breakpad(18883): M B6271000 00000000 0000E000 138271F0F6E8EE5F5C2B7D39715D13000 libselinux.so
05-06 11:59:21.452: W/google-breakpad(18883): M B627F000 00000000 00004000 4E6C8C876BA563C3C4B0B3BA562093920 libprocessgroup.so
05-06 11:59:21.455: W/google-breakpad(18883): M B6283000 00000000 0045B000 83C5B450634DDB5C4FC41CA61A35B3740 libpdfium.so
05-06 11:59:21.455: W/google-breakpad(18883): M B66E4000 00000000 00007000 F8BA9819E3B7FA0BE155985B6C09FC570 libnetutils.so
05-06 11:59:21.455: W/google-breakpad(18883): M B66EB000 00000000 00004000 6BAB6E71D6E2A765F362D19F1D6B0E990 libnetd_client.so
05-06 11:59:21.455: W/google-breakpad(18883): M B66F0000 00000000 00007000 8780B853CBEA7DCE643BD5DD81F418140 libnativehelper.so
05-06 11:59:21.455: W/google-breakpad(18883): M B66F7000 00000000 00004000 D11A32F1E80EA4A32E0F94053E4C19140 libnativebridge.so
05-06 11:59:21.455: W/google-breakpad(18883): M B66FB000 00000000 0000C000 1CA7BC0790E903E9229128A166929FEB0 libminikin.so
05-06 11:59:21.456: W/google-breakpad(18883): M B6707000 00000000 00003000 CCA8BE0D07D24523C8D02FEE5F724EA70 libmemtrack.so
05-06 11:59:21.459: W/google-breakpad(18883): M B670A000 00000000 0009C000 994A66BAAD6CB997C3F03D926ADB51870 libmedia.so
05-06 11:59:21.460: W/google-breakpad(18883): M B67A6000 00000000 00032000 89A4F06810290EEAF309C12642A3ECFA0 libjpeg.so
05-06 11:59:21.464: W/google-breakpad(18883): M B67D8000 00000000 0003C000 C5E637BD039BDA410F5348296DAAD1120 libinputflinger.so
05-06 11:59:21.464: W/google-breakpad(18883): M B6814000 00000000 0001B000 74F168649BE8583159D23A6406D107740 libinput.so
05-06 11:59:21.465: W/google-breakpad(18883): M B682F000 00000000 0000D000 5B082E821F342B59EB7E98B4A5A1B7D10 libimg_utils.so
05-06 11:59:21.466: W/google-breakpad(18883): M B683C000 00000000 00110000 1B1FD653750DE88B86D7E83095EE37160 libicuuc.so
05-06 11:59:21.467: W/google-breakpad(18883): M B6951000 00000000 00167000 237F53C12084A7F42405B410FDE8B4020 libicui18n.so
05-06 11:59:21.469: W/google-breakpad(18883): M B6AB8000 00000000 0004D000 01F66AB86D6D659031248B22951BF2670 libhwui.so
05-06 11:59:21.470: W/google-breakpad(18883): M B6B05000 00000000 00048000 AC5AE16EC01F4362C8E63DF66565090D0 libharfbuzz_ng.so
05-06 11:59:21.470: W/google-breakpad(18883): M B6B4D000 00000000 00006000 C083922E108BA32201D5D781E45EFCEE0 libhardware_legacy.so
05-06 11:59:21.471: W/google-breakpad(18883): M B6B54000 00000000 00003000 914425D16565257955F7E1574360B71F0 libhardware.so
05-06 11:59:21.473: W/google-breakpad(18883): M B6B57000 00000000 0004F000 34E1D1BEAB95ED34D0DAC916C78C0F6A0 libgui.so
05-06 11:59:21.473: W/google-breakpad(18883): M B6BA6000 00000000 00017000 B98E65710C415C83E972EBDC1EB52AC00 libexpat.so
05-06 11:59:21.473: W/google-breakpad(18883): M B6BBD000 00000000 00102000 8DBD3D1934484B7829F6D270148168210 libcrypto.so
05-06 11:59:21.473: W/google-breakpad(18883): M B6CC1000 00000000 00008000 FD57BD3754F1C9D63F3F9E1E550B9E950 libcamera_metadata.so
05-06 11:59:21.475: W/google-breakpad(18883): M B6CC9000 00000000 0003A000 116B764A83A70C0F905AA2C1D527450B0 libcamera_client.so
05-06 11:59:21.475: W/google-breakpad(18883): M B6D03000 00000000 00006000 D330B25521C028B95D7E9360F7C6D6510 libaudioutils.so
05-06 11:59:21.477: W/google-breakpad(18883): M B6D09000 00000000 00026000 12AF731CDBA8D51DC48CA7314B5B91EF0 libandroidfw.so
05-06 11:59:21.477: W/google-breakpad(18883): M B6D30000 00000000 0000B000 E2F67EE50006FD0ED1482E1463C5CCFF0 libGLESv2.so
05-06 11:59:21.478: W/google-breakpad(18883): M B6D3B000 00000000 00007000 EFE6AB19F4060BCECF8CF0E68958C2F60 libGLESv1_CM.so
05-06 11:59:21.478: W/google-breakpad(18883): M B6D42000 00000000 00004000 C91EAF69D18F0D499BD58532BBA173690 libETC1.so
05-06 11:59:21.482: W/google-breakpad(18883): M B6D47000 00000000 00068000 92714C4D425611328101DB55FDE48EFD0 libEGL.so
05-06 11:59:21.484: W/google-breakpad(18883): M B6DB2000 00000000 00018000 4939CC7D9325757DDAB52A218D55F4720 libutils.so
05-06 11:59:21.484: W/google-breakpad(18883): M B6DCA000 00000000 00004000 DFCD7772F3A5BD1E84A50C4DBFDE6F570 libstdc++.so
05-06 11:59:21.485: W/google-breakpad(18883): M B6DCE000 00000000 00019000 AE3467401278371A956801500FC8187D0 libm.so
05-06 11:59:21.487: W/google-breakpad(18883): M B6DE7000 00000000 00007000 0A492DEF82842051996A468D87F23F010 liblog.so
05-06 11:59:21.489: W/google-breakpad(18883): M B6DEE000 00000000 0000D000 A42EC33CA91FC2785E5ABDD762EF3C9B0 libcutils.so
05-06 11:59:21.491: W/google-breakpad(18883): M B6DFB000 00000000 0006D000 C7DC82C8221EE90CF1AE9DB04612A8BB0 libc.so
05-06 11:59:21.493: W/google-breakpad(18883): M B6E71000 00000000 00030000 ACC83A1C303E450D25746B59EA1167700 libbinder.so
05-06 11:59:21.496: W/google-breakpad(18883): M B6EA1000 00000000 000DF000 8FF7F2D5272201113AADA04AC076E8110 libandroid_runtime.so
05-06 11:59:21.498: W/google-breakpad(18883): M B6F85000 00000000 0000D000 8BE93C69133BBEA26AE0648C47A546F40 linker
05-06 11:59:21.498: W/google-breakpad(18883): -----END BREAKPAD MICRODUMP-----
05-06 11:59:21.499: W/AwContents(2537): onDetachedFromWindow called when already detached. Ignoring
05-06 11:59:21.501: W/GLSUser(2846): [GLSUser] Permission for com.google.android.gms to access oauth2:https://www.googleapis.com/auth/drive.appdata https://www.googleapis.com/auth/drive https://www.googleapis.com/auth/drive.apps will be managed locally.
05-06 11:59:21.507: W/art(2537): Attempt to remove local handle scope entry from IRT, ignoring
05-06 11:59:21.515: W/google-breakpad(2537): ### ### ### ### ### ### ### ### ### ### ### ### ###
05-06 11:59:21.515: W/google-breakpad(2537): Chrome build fingerprint:
05-06 11:59:21.515: W/google-breakpad(2537): 20150501_7
05-06 11:59:21.515: W/google-breakpad(2537): 447
05-06 11:59:21.515: W/google-breakpad(2537): cdd40672-1595-45ee-a623-1018fca0e2a6
05-06 11:59:21.515: W/google-breakpad(2537): ### ### ### ### ### ### ### ### ### ### ### ### ###
05-06 11:59:21.515: E/chromium(2537): ### WebView Version 42.0.2311.137 (code 2311137)
05-06 11:59:21.515: E/chromium(2537): --------- beginning of crash
05-06 11:59:21.515: A/libc(2537): Fatal signal 11 (SIGSEGV), code -6, fault addr 0x9e9 in tid 15812 (Thread-123)
05-06 11:59:21.625: I/DEBUG(1664): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
05-06 11:59:21.626: I/DEBUG(1664): Build fingerprint: 'google/hammerhead/hammerhead:5.1/LMY47I/1767468:user/release-keys'
05-06 11:59:21.626: I/DEBUG(1664): Revision: '11'
05-06 11:59:21.626: I/DEBUG(1664): ABI: 'arm'
05-06 11:59:21.626: I/DEBUG(1664): pid: 2537, tid: 15812, name: Thread-123  >>> com.-------------.-------------- <<<
05-06 11:59:21.626: I/DEBUG(1664): signal 11 (SIGSEGV), code -6 (SI_TKILL), fault addr 0x8
05-06 11:59:21.639: I/DEBUG(1664):     r0 a2090000  r1 00000000  r2 00000000  r3 00000000
05-06 11:59:21.639: I/DEBUG(1664):     r4 a2030e68  r5 00000000  r6 a6634fbc  r7 a6633e40
05-06 11:59:21.639: I/DEBUG(1664):     r8 00000000  r9 9f712be0  sl 9f712be8  fp a6297aec
05-06 11:59:21.639: I/DEBUG(1664):     ip a661dd28  sp 9f712b30  lr a547441b  pc a51957c4  cpsr 600e0030
05-06 11:59:21.640: I/DEBUG(1664): backtrace:
05-06 11:59:21.640: I/DEBUG(1664):     #00 pc 0071c7c4  /data/app/com.google.android.webview-2/lib/arm/libwebviewchromium.so
05-06 11:59:22.079: E/DataBuffer(17860): Internal data leak within a DataBuffer object detected!  Be sure to explicitly call release() on all DataBuffer extending objects when you are done with them. (internal object: com.google.android.gms.common.data.DataHolder@37c64f5d)
05-06 11:59:22.116: D/WifiService(2126): releaseWifiLockLocked: WifiLock{MetadataSyncService type=1 binder=android.os.BinderProxy@15ca8bd6}
05-06 11:59:22.368: I/DEBUG(1664): Tombstone written to: /data/tombstones/tombstone_04

**Comment by claywilkinson** [comment]
Is this Game Services related?  From the log it does not look like it.  Maybe you should post it in another repository such as https://github.com/googledrive/android-demos?
