### ISSUE TITLE
Quest progress shows negative value

### ISSUE THREAD

**Issue by volzhs** [playgameservices/android-basic-samples#143]
First of all, see this screen shot.
It shows that quest progress is -1/5.

![image](https://cloud.githubusercontent.com/assets/8281454/7730524/dac7e7c6-ff55-11e4-8f35-7eee6f72cdf5.png)

This happens when new quest comes up after early one which has same event id.
Let's assume the event id is SOME_EVENT_ID.

And app calls ``Games.Quests.load(getApiClient(), Quests.SELECT_ALL_QUESTS, Quests.SORT_ORDER_ENDING_SOON_FIRST, true);`` at start to display progress of quest in game UI.

1. make a quest with SOME_EVENT_ID and schedule 2015.01.01~2015.01.03.
2. accept this quest and make progress to 2/5 in game.
3. after 2015.01.03, quest is expired.
4. make a new quest with same SOME_EVENT_ID and schedule 2015.01.04~2015.01.06
5. accept this new quest, and exit app
6. restart app, then progress shows negative value.

**Comment by claywilkinson** [comment]
I believe that this issue has been fixed in an updated version of the Play Games App.  Please reopen this issue if it is still happening.
