### ISSUE TITLE
Issue while downloading an application from Google Play Store

### ISSUE THREAD

**Issue by tallamohan** [playgameservices/android-basic-samples#144]
Showing different values of % downloaded on "Notification bar" and "Google Play Store"
![sketch-1432205721043](https://cloud.githubusercontent.com/assets/6680479/7747417/e13b1cea-ffd7-11e4-8db7-3825fe3c74c3.jpg)

**Comment by samtstern** [comment]
Closing this issue, is is not related to the samples but is an issue with the Play Store.
