### ISSUE TITLE
Push notifications not working (Gmail, CloudMagic etc.) after update to GServices 7.5.71 on 5.1 Nexus 4/5

### ISSUE THREAD

**Issue by IncorporateApps** [playgameservices/android-basic-samples#145]
After the automated update to 7.5.71 no notifications are being shown in the toolbar or the lock screen.

**Comment by IncorporateApps** [comment]
After downgrade to 7.3. problem resolved, definitely an issue with 7.5.71

**Comment by samtstern** [comment]
@IncorporateApps I am going to close this issue because I do not think it is related to `android-basic-samples` but rather to Google Play Services in general.

**Comment by IncorporateApps** [comment]
Where do we report Google Play Services  issues?

**Comment by samtstern** [comment]
On your phone open the "Google Settings" app, then click the three-dot menu in the upper right hand corner and select "Help and Feedback"
