### ISSUE TITLE
Want to create Custom UI for Turn based games using playgamesservices 

### ISSUE THREAD

**Issue by ravindranalwaya** [playgameservices/android-basic-samples#146]
Hi Team,
I am developing a game using playgamesservices. I am using leader-board,achievements,turn based etc for my game. I have downloaded BasicSamples SkeletonActivity, Its working fine. But how to get custom ui for the all available inbox matches. 
TurnBasedMultiplayer interface have getInboxIntent(GoogleApiClient apiClient) method which is returning Intent. After getting intent, below method called.which is giving default UI for all available inbox matches. 
 startActivityForResult(intent, RC_LOOK_AT_MATCHES);
How to get all available inbox matches so that we can show them as our own UI(for ex. using RecycleView).
I have attached image for the API and default look for getInboxIntent(GoogleApiClient apiClient). 
![getinboxintentapi](https://cloud.githubusercontent.com/assets/11533024/8076637/154ed190-0f6c-11e5-91be-e199c12cc273.jpg)
![turnbased](https://cloud.githubusercontent.com/assets/11533024/8076638/154f67a4-0f6c-11e5-93ac-f5e127f14e9a.jpg)

**Comment by jorgelamb** [comment]
You should check `loadMatchesByStatus` method from `TurnBasedMultiplayer`.
https://developers.google.com/android/reference/com/google/android/gms/games/multiplayer/turnbased/TurnBasedMultiplayer#loadMatchesByStatus(com.google.android.gms.common.api.GoogleApiClient%2C%20int%2C%20int%5B%5D)

You can also register a listener for updates on the games.

**Comment by ravindranalwaya** [comment]
Hi Jorge,
I am able to get all match details now using loadMatchesByStatus method. it was really helpful.. thanks.

**Comment by jorgelamb** [comment]
Good to know it helped you!

I guess this issue can be closed now, but I can't do it. Can you do that?
