### ISSUE TITLE
Different Result Codes for same action: Disconnection inside Games.Leaderboards.getAllLeaderboardsIntent

### ISSUE THREAD

**Issue by lucas-carneiro** [playgameservices/android-basic-samples#152]
When a player disconnects from Google Play Services using the disconnect button inside a Google Leaderboard UI (Games.Leaderboards.getAllLeaderboardsIntent), two different result codes can be returned to Activity.onActivityResult:
- GamesActivityResultCodes.RESULT_RECONNECT_REQUIRED (Code 10001)
- Activity.RESULT_CANCELED (Code 0)

<br>
The first code is returned when a user makes the action below:

> **Action 1**
> User clicks on Settings, and then uses the Log Out button.
> <img src="http://i.imgur.com/XwQ3RD4.png" width="270" height="480" /> <img src="http://i.imgur.com/zDIutpt.png" width="270" height="480" />

<br>
The second code is returned when a user makes the action below:

> **Action 2**
> User clicks on a specific leaderboard, clicks on Settings, and then uses the Log Out button.
> <img src="http://i.imgur.com/a7tmrXD.png" width="270" height="480" /> <img src="http://i.imgur.com/zDIutpt.png" width="270" height="480" />

<br>
When a user takes action 1, the Google Leaderboard UI closes, returning code 10001. When action 2 is taken, only the specific leaderboard UI closes, going back to "home screen" (where the user can choose a specific leaderboard). For action 2, it is necessary for the user to close the Google Leaderboard UI, returning code 0 instead of the correct code for this disconnection (10001).
<br>
Because of that, it is possible to have 2 different codes when a user disconnects from Google Play Services using the Google Leadeboard UI.

<br>
With this problem, it is not possible to verify if is necessary to disconnect from Google Services API, allowing a inconsistent state. See the example below:

```
protected void onActivityResult(int requestCode, int resultCode, Intent intent) {
        if (requestCode == RC_SIGN_IN) {
            mSignInClicked = false;
            mResolvingConnectionFailure = false;
        }
        switch (resultCode){
            case RESULT_OK:
                // Everything worked fine
                mGoogleApiClient.connect();
                break;
            case RESULT_CANCELED:
                // 2 Options:
                //  - Everything worked fine;
                //  - It is necessary to reconnect to google services api (Code 10001).
                // It is not possible to know which option happened.
                break;
            case GamesActivityResultCodes.RESULT_RECONNECT_REQUIRED:
                // Force a disconnect to sync up state
                mGoogleApiClient.disconnect();
                break;
            default:
                // Bring up an error dialog to alert the user that sign-in failed.
                BaseGameUtils.showActivityResultError(this, requestCode, resultCode, R.string.sign_in_failed);
        }
    }
```

**Comment by samtstern** [comment]
I will report this internally, this is very interesting.  Thank you for the detailed report.

**Comment by mwgray** [comment]
I just tried to reproduce, only received the 10001 result.  Closing!
