### ISSUE TITLE
Linking Android app to game services stopped working.

### ISSUE THREAD

**Issue by stolk** [playgameservices/android-basic-samples#153]
Using google play developer console, it is no longer possible to link an app by providing key's SHA1 fingerprint.

This worked two days ago, but yesterday and today, it will only respond with an error message:
**An unexpected error occurred. Please try again later. (4800001)**

![error](https://cloud.githubusercontent.com/assets/455280/9476105/c3246ee4-4b1f-11e5-8f51-440e2fa00d75.png)

**Comment by claywilkinson** [comment]
I tried an existing app and it worked ok - is this only on new apps?

**Comment by stolk** [comment]
Thanks for trying.
I am using an existing app as well.

two days ago I made a new app, and could link client ids.
before that I added game services to an existing one, worker fine.
 
When I tried to add game services to another existing app yesterday, I only get error codes back.
(BTW, the 3 APIs do get enabled, I can see on the 'google developer console', just no oath2 fingerprints.)

Do you know what the 4800001 code means? Where can I look it up?
Thx,

 bram

**Comment by claywilkinson** [comment]
Unfortunately 4800001 is a generic error so there is not a lot to go on.
A couple questions which will help narrow down the issue:
1. does this happen only when you leave the fingerprint field empty? or does it happen before you get to this page?
2. Does it happen if you are trying to add only android apps, or does it happen when you try to add other kinds?
3. is it possible that the contact email does not match the user's email that is signed in?

Thanks!
Clayton

**Comment by stolk** [comment]
1. It happens after supplying the finger print. Entering either debug finger print or release finger print results in this error.

2. So far I only tried android apps. I have not used Games Services with iOS yet.

3. Aaaaaahhhhh! Yes... that is indeed a difference between app X, which successfully linked android client ids, and app Y, which gives this error. In the 'store page' section of my app I had a different contact email. I will change this, but I am very surprised this could affect the workings of app linking. Both apps are under the same google play account, I just have  a different 'contact' email, which is customer facing, and used for public display! This really should never affect how apps clientids are linked.

I've published my app again, with different email addr, and will try again when the submission goes live.

Thank you for your help, I appreciate it a lot!

  Bram

**Comment by claywilkinson** [comment]
Great! thanks for the help.  I've been told they are rolling back the change on the console that caused the problem and they'll fix it.

**Comment by stolk** [comment]
Uh.... so the email address was not the issue. I changed the email addr, and tried again.

I still get an error, but strangely enough, there is no error code any more.
The (4800001) part is gone!

![error2](https://cloud.githubusercontent.com/assets/455280/9480725/8cc348d8-4b39-11e5-929c-d17b6813bfb9.png)

**Comment by claywilkinson** [comment]
ok - they are planning to revert the change causing the problem - i will pass along your comments.

**Comment by stolk** [comment]
Clayton, 

I just tried it again, and now it works again.
Thank you for helping out.

  Bram
