### ISSUE TITLE
Room UI is sometimes slow to open.

### ISSUE THREAD

**Issue by stolk** [playgameservices/android-basic-samples#154]
When I create a room and display its UI, sometimes it is pretty slow to do so.
(At other times, it is faster.)
I've examined the logs, to see what is going on during that time.

Several things bother me, from this log.
For one thing, there is a 'Class not found when unmarshalling' error, which I wrote up here:
https://github.com/playgameservices/cpp-android-basic-samples/issues/17

But the real reason for slow response seems to be an HTTP time out of 5s to www.googleapis.com site.

Also, it actually looks like there is some email communication going on?
From libjingle: 

```
D/Volley  ( 6095): [733] BasicNetwork.logSlowRequests: HTTP response for request=<[ ] https://www.googleapis.com/games/v1/rooms/create?language=en_US 0x30b75e1c NORMAL 435> [lifetime=5010], [size=639], [rc=200], [retryCount=0]
D/Volley  ( 6095): [1] Request.finish: 5042 ms: [ ] https://www.googleapis.com/games/v1/rooms/create?language=en_US 0x30b75e1c NORMAL 435
I/libjingle( 6512): virtual int games_rtmp::BuzzSubscriptionsTask::SetOnDisconnectTask::ProcessStart(): Send-on-disconnect: <cli:message to="games@ob.talk.google.com" type="headline" xmlns:cli="jabber:client"><push xmlns="google:push" channel="games.google.com/buzzbot" sendOnDisconnect="true"><recipient to="play-presence@games.bot.talk.google.com">Q2hvS0NRajFqT1hubWhzUUFoQUJHQUFnX19fX19fX19fX19fQVJES18tbTJ5TXFodmhjOmdhbWVzQG9iLnRhbGsuZ29vZ2xlLmNvbS9nYW1lc19hbmRyRThFMjVDQkY=</recipient></push></cli:message>
```

Who are games@ob.talk.google.com and play-presence@games.bot.talk.google.com, and why are they getting email when I create a room?

Also, I looked up libjingle: it is a shuttered projected, that has long been replaced by google hangouts? Should that not have been removed from game services? I am using 1.4.1 of gpg.

Thanks,

  Bram

**Comment by stolk** [comment]
Here is a more complete log from the device (Samsung Galaxy Note 4)

```
I/swaag   (28707): StateManager::onNetworkMatch
D/ChimeraCfgMgr( 6095): Loading module com.google.android.gms.games from APK com.google.android.play.games
D/ChimeraModuleLdr( 6095): Module APK com.google.android.play.games already loaded
I/libjingle( 6512): virtual int games_rtmp::BuzzSubscriptionsTask::SetOnDisconnectTask::ProcessStart(): Send-on-disconnect: <cli:message to="games@ob.talk.google.com" type="headline" xmlns:cli="jabber:client"><push xmlns="google:push" channel="games.google.com/buzzbot" sendOnDisconnect="true"><recipient to="play-presence@games.bot.talk.google.com" remove="true"/></push></cli:message>
D/UiModeManager(  935): mCoverManager.getCoverState() : true
V/GamesNativeSDK(28707): Detaching from JVM on thread main_dispatch
D/Volley  ( 6095): [733] BasicNetwork.logSlowRequests: HTTP response for request=<[ ] https://www.googleapis.com/games/v1/rooms/create?language=en_US 0x30b75e1c NORMAL 435> [lifetime=5010], [size=639], [rc=200], [retryCount=0]
D/Volley  ( 6095): [1] Request.finish: 5042 ms: [ ] https://www.googleapis.com/games/v1/rooms/create?language=en_US 0x30b75e1c NORMAL 435
I/libjingle( 6512): virtual int games_rtmp::BuzzSubscriptionsTask::SetOnDisconnectTask::ProcessStart(): Send-on-disconnect: <cli:message to="games@ob.talk.google.com" type="headline" xmlns:cli="jabber:client"><push xmlns="google:push" channel="games.google.com/buzzbot" sendOnDisconnect="true"><recipient to="play-presence@games.bot.talk.google.com">Q2hvS0NRajFqT1hubWhzUUFoQUJHQUFnX19fX19fX19fX19fQVJES18tbTJ5TXFodmhjOmdhbWVzQG9iLnRhbGsuZ29vZ2xlLmNvbS9nYW1lc19hbmRyRThFMjVDQkY=</recipient></push></cli:message>
I/swaag   (28707): created a room 1
E/Parcel  (  935): Class not found when unmarshalling: com.google.android.gms.games.multiplayer.realtime.RoomEntity
E/Parcel  (  935): java.lang.ClassNotFoundException: com.google.android.gms.games.multiplayer.realtime.RoomEntity
E/Parcel  (  935): 	at java.lang.Class.classForName(Native Method)
E/Parcel  (  935): 	at java.lang.Class.forName(Class.java:251)
E/Parcel  (  935): 	at java.lang.Class.forName(Class.java:216)
E/Parcel  (  935): 	at android.os.Parcel.readParcelableCreator(Parcel.java:2133)
E/Parcel  (  935): 	at android.os.Parcel.readParcelable(Parcel.java:2097)
E/Parcel  (  935): 	at android.os.Parcel.readValue(Parcel.java:2013)
E/Parcel  (  935): 	at android.os.Parcel.readArrayMapInternal(Parcel.java:2314)
E/Parcel  (  935): 	at android.os.Bundle.unparcel(Bundle.java:249)
E/Parcel  (  935): 	at android.os.Bundle.getString(Bundle.java:1118)
E/Parcel  (  935): 	at android.content.Intent.getStringExtra(Intent.java:5285)
E/Parcel  (  935): 	at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:1586)
E/Parcel  (  935): 	at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:1167)
E/Parcel  (  935): 	at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:4507)
E/Parcel  (  935): 	at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:4389)
E/Parcel  (  935): 	at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:161)
E/Parcel  (  935): 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3013)
E/Parcel  (  935): 	at android.os.Binder.execTransact(Binder.java:404)
E/Parcel  (  935): 	at dalvik.system.NativeStart.run(Native Method)
E/Parcel  (  935): Caused by: java.lang.NoClassDefFoundError: com/google/android/gms/games/multiplayer/realtime/RoomEntity
E/Parcel  (  935): 	... 18 more
E/Parcel  (  935): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.games.multiplayer.realtime.RoomEntity" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
E/Parcel  (  935): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/Parcel  (  935): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
E/Parcel  (  935): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
E/Parcel  (  935): 	... 18 more
V/ApplicationPolicy(  935): isApplicationStateBlocked userId 0 pkgname com.google.android.play.games
W/ActivityManager(  935): mDVFSHelper.acquire()
I/swaag   (28707): CMD_PAUSE handled
I/swaag   (28707): CMD_LOST_FOCUS handled
```

**Comment by claywilkinson** [comment]
Good questions.  First of all, I am presuming you are writing an app using the native C++ SDK and cross-posting to here, right?

The missing classes are a problem.  In a native application, you still need to include the play services library project in your project.  Detailed instructions for setting up the project is at https://developers.google.com/games/services/cpp/gettingStartedAndroid. 

The slow response has so many possible causes I can't start to guess.  This particular call looks like a registration of the player's presence.  It could be that the message was sent fast and there is some processing of the registration before the response is sent, again. I am not too concerned about that.  Does it appear to slow down the UI display or just the data loading?

You are correct, libjingle is no longer a public project.  I am not sure of the full story of why, but I think it has to do with so many real time APIs, that it was abandoned in favor another protocol.  With that said, Google uses it internally for implementing the multiplayer game services which is OK since the multi-player APIs are not inter-operable with other APIs.

games and play-presence are not getting email, but are messaging endpoints via libjingle to communicate the game state with other players.

**Comment by stolk** [comment]
Thanks Clayton,

I apologize for x-post, yes, I am on C++ SDK, and went here as I thought there would be overlap, and the issues list on the cpp github don't seem to get monitored by Google people. And I did notice your prompt reply here yesterday, on the dev console issue. I'm sorry.

I do include the play services library project (see below) and I've seen this error also on the ButtonClicker example from google, not just my own project.

I got the google-play-services_lib project from the extras/google/google_play_services/libproject/ directory from the latest android SDK, API 23.

As you can see, 'dex' takes google-play-services.jar as input, and disassembling it did show the missing class:
```
public final class com.google.android.gms.games.multiplayer.realtime.RoomEntity extends com.google.android.gms.games.internal.GamesDowngradeableSafeParcel implements com.google.android.gms.games.multiplayer.realtime.Room {
```

The slow down is just occasional, so yeah, I will ignore it for now. I think the actual room creation is slow, not just the UI displaying.

OK, good to know that there is no actual email going on to setup the p2p.

Thanks for your help, I really appreciate it.

  Bram

```
      [dex] input: /home/bram/apps/Buggy/Android/bin/classes
      [dex] input: /home/bram/apps/Buggy/Android/google-play-services_lib/bin/classes.jar
      [dex] input: /home/bram/apps/Buggy/Android/google-play-services_lib/libs/google-play-services.jar
      [dex] Pre-Dexing /home/bram/apps/Buggy/Android/google-play-services_lib/bin/classes.jar -> classes-da57b824bfbfd61fb0f5087c84529e16.jar
       [dx] Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
      [dex] Pre-Dexing /home/bram/apps/Buggy/Android/google-play-services_lib/libs/google-play-services.jar -> google-play-services-eef5d4543fb974495e61b5909ddcfb0c.jar
       [dx] Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
      [dex] Converting compiled files and external libraries into /home/bram/apps/Buggy/Android/bin/classes.dex...
       [dx] Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
       [dx] Merged dex A (25 defs/23.6KiB) with dex B (1 defs/0.4KiB). Result is 26 defs/27.0KiB. Took 0.0s
       [dx] Merged dex A (26 defs/27.0KiB) with dex B (5199 defs/4457.4KiB). Result is 5225 defs/5279.9KiB. Took 0.3s
```

**Comment by claywilkinson** [comment]
Thanks for the details on the build - I'll take a look also.  No problem on the cross-post, we keep our eyes on all the repos in playgameservices :)

**Comment by stolk** [comment]
I've confirmed that the class actually makes it into my 
>bin/dexedLibs/google-play-services-eef5d4543fb974495e61b5909ddcfb0c.jar

This means, that it is bound to be the path that is the issue, not the file itself?
The log says:
> path: DexPathList[[directory "."],nativeLibraryDirectories=[/vendor/lib, /system/lib]]

Maybe it is not supposed to be unmarshalled from the '.' directory?
Guessing here, though, because I am not familiar with this unmarshalling procedure.

I must also note, that the Room UI does show up: I see my avatar show up, and an empty slot for an opponent. So I'm not sure what the effect of the missing class is on the working of the app.

  Bram

**Comment by claywilkinson** [comment]
I pinged the engineering team on this one - they still do not have an update.

**Comment by stolk** [comment]
Sorry, you can close this.
I no longer see 'slow to open' UIs.
