### ISSUE TITLE
No resource found that matches the given name (at 'drawable' with value '@drawable/common_signin_btn_icon_disabled_focus_light').

### ISSUE THREAD

**Issue by lucamtudor** [playgameservices/android-basic-samples#165]
When I try to run the TypeANumber example I get the following error:

> C:\Users\Tudor\00.DevCenter\Android\Projects\sandbox\android-basic-samples\BasicSamples\libraries\BaseGameUtils\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\8.1.0\res\drawable\common_signin_btn_icon_light.xml
> Error:(9, 27) No resource found that matches the given name (at 'drawable' with value '@drawable/common_signin_btn_icon_disabled_focus_light').
> 
> C:\Users\Tudor\00.DevCenter\Android\Projects\sandbox\android-basic-samples\BasicSamples\libraries\BaseGameUtils\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\8.1.0\res\drawable\common_signin_btn_text_light.xml
> Error:(9, 27) No resource found that matches the given name (at 'drawable' with value '@drawable/common_signin_btn_text_disabled_focus_light').
> 
> Error:Execution failed for task ':libraries:BaseGameUtils:processReleaseResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Users\Tudor\00.DevCenter\Android\sdk\build-tools\23.0.1\aapt.exe'' finished with non-zero exit value 1

I'm runing Android Studio 1.4 RC 3, build number AI-141.2279206, Android SDK Tools 24.3.4

**Comment by mwgray** [comment]
This should be resolved with latest; closing.
