### ISSUE TITLE
No methods to get snapshot ID

### ISSUE THREAD

**Issue by Motoban** [playgameservices/android-basic-samples#169]
The following method:

```
Games.Snapshots.resolveConflict (GoogleApiClient apiClient, String conflictId, String snapshotId, SnapshotMetadataChange metadataChange, SnapshotContents snapshotContents)
```

requires snapshotId as a parameter, but there are no methods like getID() or getSnapshotID() in Snapshot, SnapshotMetadata and OpenSnapshotResult interfaces.

**Comment by Motoban** [comment]
It seems there are no simple ways to get snapshot ID.

A possible solution is provided there:
http://stackoverflow.com/questions/32823470/snapshotid-for-resolveconflict-in-google-play-saved-games

**Comment by claywilkinson** [comment]
OpenSnapshotResult has getConflictId().  See: https://developers.google.com/android/reference/com/google/android/gms/games/snapshot/Snapshots.OpenSnapshotResult
