### ISSUE TITLE
Repeated exception causing high battery drain by Google Play Services

### ISSUE THREAD

**Issue by scoof** [playgameservices/android-basic-samples#170]
PID 3250, com.google.android.gms.persistent logs this almost once per second. Uninstalling/reinstalling updates of Google Play Services seems to have fixed it for the time being.

E/SQLiteLog( 3250): (2067) abort at 35 in [INSERT INTO context(context_name,end_time,context_family,module_id,version,sync_state_mod_time_millis,start_time,sync_state,context_id,time_type,proto_blob) VALUES (?,?,?,?,?,?,?,?,?,?,?)]: UNI
I/Babel   ( 5969): RTCS will handle all server updates.
E/SQLiteDatabase( 3250): Error inserting context_name=6 end_time=1443720116002 context_family=1 module_id=com.google.android.contextmanager.module.DetectedActivityProducer version=1 sync_state_mod_time_millis=1443720116026 start_time=1443720109438 sync_state=0 context_id=12459098-4795-453e-b26b-e89b270f2fd6 time_type=3 proto_blob=[B@3a0a1697
E/SQLiteDatabase( 3250): android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: context.context_id (code 2067)
E/SQLiteDatabase( 3250):        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
E/SQLiteDatabase( 3250):        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
E/SQLiteDatabase( 3250):        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
E/SQLiteDatabase( 3250):        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
E/SQLiteDatabase( 3250):        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1471)
E/SQLiteDatabase( 3250):        at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1341)
E/SQLiteDatabase( 3250):        at com.google.android.contextmanager.q.al.a(SourceFile:408)
E/SQLiteDatabase( 3250):        at com.google.android.contextmanager.q.al.b(SourceFile:383)
E/SQLiteDatabase( 3250):        at com.google.android.contextmanager.q.al.a(SourceFile:349)
E/SQLiteDatabase( 3250):        at com.google.android.contextmanager.q.al.b(SourceFile:376)
E/SQLiteDatabase( 3250):        at com.google.android.contextmanager.g.a.j.a(SourceFile:58)
E/SQLiteDatabase( 3250):        at com.google.android.contextmanager.g.a.a.run(SourceFile:52)
E/SQLiteDatabase( 3250):        at com.google.android.contextmanager.g.i.handleMessage(SourceFile:215)
E/SQLiteDatabase( 3250):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/SQLiteDatabase( 3250):        at android.os.Looper.loop(Looper.java:135)
E/SQLiteDatabase( 3250):        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by claywilkinson** [comment]
Thanks for the info - I'll pass it along.

**Comment by scoof** [comment]
8.1.15 (2250156-230)
3.3.58 (228594-030)

**Comment by christocracy** [comment]
Seeing this too.  I've seen it on play-services versions `7.5.0` to `8.3.0`

**Comment by mrkam** [comment]
12-23 21:35:26.939 1891-7775/? E/SQLiteDatabase: Error inserting time_type=3 proto_blob=[B@42ad7408 sync_state_mod_time_millis=1450935326944 context_id=a94889f6-ae62-468a-be68-62873adfebcc end_time=1450934905149 module_id=com.google.android.contextmanager.module.DetectedActivityProducer start_time=1450934843841 sync_state=0 context_family=1 context_name=6 version=1
                                                 android.database.sqlite.SQLiteConstraintException: column context_id is not unique (code 19)
                                                     at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
                                                     at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:972)
                                                     at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
                                                     at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
                                                     at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1590)
                                                     at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1460)
                                                     at com.google.android.contextmanager.q.ak.a(SourceFile:445)
                                                     at com.google.android.contextmanager.q.ak.b(SourceFile:420)
                                                     at com.google.android.contextmanager.q.ak.a(SourceFile:370)
                                                     at com.google.android.contextmanager.q.ak.b(SourceFile:400)
                                                     at com.google.android.contextmanager.q.r.a(SourceFile:381)
                                                     at com.google.android.contextmanager.g.a.j.a(SourceFile:58)
                                                     at com.google.android.contextmanager.g.a.a.run(SourceFile:52)
                                                     at com.google.android.contextmanager.g.i.a(SourceFile:263)
                                                     at com.google.android.contextmanager.g.i.handleMessage(SourceFile:254)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:146)
                                                     at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by claywilkinson** [comment]
I checked with some engineers working on Android, and while it is ugly, these errors are expected during an upgrade path of some internal data.  It does not appear to the be the cause of the battery drain.

**Comment by scoof** [comment]
Is it expected that these continue for days? That's what I was seeing at the time.

**Comment by micheljung** [comment]
I'm getting this error since weeks

```
01-17 16:24:03.091  2137  3519 E SQLiteDatabase: Error inserting context_name=6 end_time=1453043684182 context_family=1 module_id=com.google.android.contextmanager.module.DetectedActivityProducer version=1 sync_state_mod_time_millis=1453044243088 start_time=1453043630271 sync_state=0 context_id=92912b06-0031-4443-9eb1-aa3e05d47a42 time_type=3 proto_blob=[B@cd542d9
01-17 16:24:03.091  2137  3519 E SQLiteDatabase: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: context.context_id (code 2067)
01-17 16:24:03.091  2137  3519 E SQLiteDatabase: 	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
01-17 16:24:03.091  2137  3519 E SQLiteDatabase: 	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:780)
01-17 16:24:03.091  2137  3519 E SQLiteDatabase: 	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
01-17 16:24:03.091  2137  3519 E SQLiteDatabase: 	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
01-17 16:24:03.091  2137  3519 E SQLiteDatabase: 	at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1471)
01-17 16:24:03.091  2137  3519 E SQLiteDatabase: 	at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1341)
01-17 16:24:03.091  2137  3519 E SQLiteDatabase: 	at com.google.android.contextmanager.q.ak.a(SourceFile:445)
01-17 16:24:03.091  2137  3519 E SQLiteDatabase: 	at com.google.android.contextmanager.q.ak.b(SourceFile:420)
01-17 16:24:03.091  2137  3519 E SQLiteDatabase: 	at com.google.android.contextmanager.q.ak.a(SourceFile:370)
01-17 16:24:03.091  2137  3519 E SQLiteDatabase: 	at com.google.android.contextmanager.q.ak.b(SourceFile:400)
01-17 16:24:03.091  2137  3519 E SQLiteDatabase: 	at com.google.android.contextmanager.q.r.a(SourceFile:381)
01-17 16:24:03.091  2137  3519 E SQLiteDatabase: 	at com.google.android.contextmanager.g.a.j.a(SourceFile:58)
01-17 16:24:03.091  2137  3519 E SQLiteDatabase: 	at com.google.android.contextmanager.g.a.a.run(SourceFile:52)
01-17 16:24:03.091  2137  3519 E SQLiteDatabase: 	at com.google.android.contextmanager.g.i.a(SourceFile:263)
01-17 16:24:03.091  2137  3519 E SQLiteDatabase: 	at com.google.android.contextmanager.g.i.handleMessage(SourceFile:254)
01-17 16:24:03.091  2137  3519 E SQLiteDatabase: 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-17 16:24:03.091  2137  3519 E SQLiteDatabase: 	at android.os.Looper.loop(Looper.java:148)
01-17 16:24:03.091  2137  3519 E SQLiteDatabase: 	at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by tali3san** [comment]
Same here, I see these all the time in my Android logs. This was even after moving my account/data from a Nexus 5 to a Nexus 5X.  Is there any way to delete this database?

**Comment by Fry-kun** [comment]
Appears to be permanent, seeing these in my logcat all the time

**Comment by scoof** [comment]
@claywilkinson This is definitely not a temporary issue. New phone exhibits same behavior, though the amount of logged exceptions has fallen.

**Comment by haridsv** [comment]
I am also seeing these for a very long time and my phone has been in use for about an year with the same Android version. I don't think these are related to any upgrade.
