### ISSUE TITLE
amount of snapshots

### ISSUE THREAD

**Issue by otez-jedi** [playgameservices/android-basic-samples#173]
is there a way to know the amount of snapshots before calling the 'select snapshot' intent?

**Comment by claywilkinson** [comment]
You can call [Games.Snapshots.load()](https://developers.google.com/android/reference/com/google/android/gms/games/snapshot/Snapshots.html#load(com.google.android.gms.common.api.GoogleApiClient, boolean)).  This will return all the metadata for the saved games.

**Comment by otez-jedi** [comment]
thanks! that worked
