### ISSUE TITLE
google_play_services_version does not have a corresponding integers.xml file

### ISSUE THREAD

**Issue by Lard4** [playgameservices/android-basic-samples#174]

**Comment by claywilkinson** [comment]
I am not sure what you are asking, but I guess it is the location of the value of google_play_services_version?  This is in res/values/version.xml.

**Comment by Punchieo** [comment]
In the manifest, it references @integer/google_play_services_version
As far as I can see, the integers.XML file is nonexistent.

**Comment by claywilkinson** [comment]
Once you run the Setup (Window > Google Play Games > Setup > Android Setup..) it will copy the google play services client library into the project.  That client library contains the version.xml file defining that value.

**Comment by mwgray** [comment]
Closing, Android Studio should handle this now.
