### ISSUE TITLE
Backend error - "Green circle of death"

### ISSUE THREAD

**Issue by jorgelamb** [playgameservices/android-basic-samples#175]
Hi,

Sometimes our users report that they get an error which prevents them from playing our game. We already refer to it as "green circle of death" because of its effect.
 
While loading the games, there's a spinner circle in the app. Once the games are loaded the spinner is removed and the games are listed. Sometimes this game loading takes 15 seconds and then shows an empty game list (when there should be many games). Sometimes just rebooting the phone fixes the problem, but other times it isn't fixed with that, and not even clearing application data (from play games, our game, and play services cache) works.

After the 15 seconds timeout an empty list of games is returned. If a game is created from that state, the game is received by the opponents and they can play, but the user having issues doesn't get any update or notification. If the application is restarted then after the 15 seconds timeout it shows the new set of games which can't be played because with no updates it's never your turn. 

One important thing is that the same happens when going to "Inbox" on Google Play Games app, so it doesn't look like an error in our application. When some user is affected, it happens in both our application and in Google Play Games. Other option from Google Play Games app is to report "No Internet connection, try again" even when there's good internet connection from the device.

Other players from same device can play ok (adding an extra account to android, with full list of apps and everything).

This time I'm getting the error in my own account so I can provide some logs:

10-19 18:48:48.621  2886  4808 D Volley  : [118] BasicNetwork.logSlowRequests: HTTP response for request=<[ ] https://www.googleapis.com/games/v1whitelisted/multiplayerentities/sync?language=en_US&matchType=real_time&matchType=turn_based&maxCompletedMatchesPerApp=10&platformType=ANDROID&requestingApplicationId=691821631106 0x30b75e1c NORMAL 2591> [lifetime=15326], [size=122], [rc=500], [retryCount=0]
10-19 18:48:48.621  2886  4808 E Volley  : [118] BasicNetwork.performRequest: Unexpected response code 500 for https://www.googleapis.com/games/v1whitelisted/multiplayerentities/sync?language=en_US&matchType=real_time&matchType=turn_based&maxCompletedMatchesPerApp=10&platformType=ANDROID&requestingApplicationId=691821631106
10-19 18:48:48.622  2886  2886 D Volley  : [1] Request.finish: 15327 ms: [ ] https://www.googleapis.com/games/v1whitelisted/multiplayerentities/sync?language=en_US&matchType=real_time&matchType=turn_based&maxCompletedMatchesPerApp=10&platformType=ANDROID&requestingApplicationId=691821631106 0x30b75e1c NORMAL 2591
10-19 18:48:48.624  2886 19181 W MultiplayerAgent: {"errors":[{"domain":"global","reason":"backendError","message":"Backend Error"}],"code":500}

One theory we have is that playing with low cellphone signal / wifi (ie. getting in an elevator) can start the issue, but it doesn't always happen, and it should be ok once the signal / wifi is recovered.

Is anyone else getting this kind of errors? What else can we do when we get this issue to debug it?

Jorge

**Comment by claywilkinson** [comment]
This was due to a server side issue that was resolved.
