### ISSUE TITLE
CollectAllTheStars2: Missing information in the readme file for setting up project

### ISSUE THREAD

**Issue by Shanannigans** [playgameservices/android-basic-samples#186]
I spend a whole day trying to get this save game example to run, because there is information missing in the documentation that is needed to set the game up, please update your readme file:

- The documentation doesn't say that you need to add the project to the Google developer console also, not only to the Google Play Developer Console in order to activate the APIs

- In Google Developer console, I had to enable the Google Drive API for this project, else I would get an error like {statusCode=INTERNAL_ERROR,     resolution=null}

- In the Google Play Developer console in Game Services -> Game Details, the setting "saved games" (currently below category) also needs to be activated, this was not activated in my new project by default, therefore I got an "Cannot use snapshots without enabling the 'Saved Game' feature in the Play console" - error

![unbenannt](https://cloud.githubusercontent.com/assets/11243110/11767190/a3e2541a-a1a5-11e5-8314-d5272bf97423.PNG)

**Comment by claywilkinson** [comment]
Thanks for the detailed feedback.  I'll add it to the list of things to update.  In the mean time, please feel free to submit a pull request.

**Comment by gguuss** [comment]
This should be fixed in the recent updates to the [project readme](https://github.com/playgameservices/android-basic-samples/blob/master/BasicSamples/CollectAllTheStars2/README.md).
