### ISSUE TITLE
How to run the make_eclipse_compat script correctly?

### ISSUE THREAD

**Issue by serge144** [playgameservices/android-basic-samples#188]
Hey everyone,

I have tried to run this script in many ways but still don't work, First times i just clicked it or ran the command lines from the folder where it is located but the error says the command line has to be run from the main folder "android-basic-samples-master". 
And so i open the main folder called "android-basic-samples-master" and from there open a new
command terminal on windows OS. Then i insert just as instructed the following command:
"Scripts/make_eclipse_compat.cmd"  (.cmd because it's on windows) but it says the following:
"Scripts is not recognized as an internal or external command" 

This looks so simple but yet so hard... all i want is to run a script lol..

Thank you
Best Regards
Serge

**Comment by claywilkinson** [comment]
Very strange.  Just out of curiosity, why not use Android Studio and Gradle?

The easiest thing to do might be to manually copy the files vs. using the script.
1. make a directory eclipse_compat.  This is where the Eclipse project will be.

For each sample **and** libraries\BaseGameUtils do the following: (I'll use ButtonClicker as the example)

1. Make a directory for the sample:

         `mkdir eclipse_compat\ButtonClicker`
2. Copy the android manifest for the sample: 

 `copy BasicSamples\ButtonClicker\src\main\AndroidManifest.xml eclipse_compat\ButtonClicker`

3. Copy the resources:

`mkdir eclipse_compat\ButtonClicker\res`
`xcopy /e /i BasicSamples\ButtonClicker\src\main\res\*.* eclipse_compat\ButtonClicker\res`

4. Copy the java source

`mkdir eclipse_compat\ButtonClicker\src`
`xcopy /e /i BasicSamples\ButtonClicker\src\main\java\*.* eclipse_compat\ButtonClicker\src`

5. Copy the app compat library

`mkdir eclipse_compat\ButtonClicker\libs`
`xcopy /e /i Scripts\eclipse_aux\*.jar eclipse_compat\ButtonClicker\libs`
