### ISSUE TITLE
An unexpected error occurred. Please try again later. (4800004)

### ISSUE THREAD

**Issue by OmerCeliker** [playgameservices/android-basic-samples#189]
Hello,

I am getting the error title above, while I try to add google play services to my application using
google play developer console->Game Services->Mochiland->linked apps->authorize your app now

I have already submitted another bug report for this but did not hear from anyone at google yet.
The package name is com.jujubiz.mochiland

I was trying to enable the advertisement for Ads Badging. It will not let me save the flag for it
unless I have the game services working first. I am stuck at the moment.

Can you make your error messages more descriptive overall? Google should have a lookup table for all its error messages.

**Comment by claywilkinson** [comment]
Thanks for the feedback.  I have passed along the information, but I have not heard of any update yet.

Is it possible that that package name and SHA1 fingerprint have been registered before?

**Comment by OmerCeliker** [comment]
No.

**Comment by OmerCeliker** [comment]
Let me correct my answer. I am not sure.

**Comment by chandruscm** [comment]
You'd encounter this error when you are re-registering with the same package name (i.e when you delete a game service and add a new one with the same name ). Check if your project has been already registered in https://console.developers.google.com/ Any project you delete, takes effect only after 7-days.

**Comment by claywilkinson** [comment]
Closing this one.  Please reopen if you still cannot publish.
