### ISSUE TITLE
Snapshots strange behaviour

### ISSUE THREAD

**Issue by DummyCo** [playgameservices/android-basic-samples#190]
Hi. I’m trying to set up cross-device saves synchronization and I’m facing strange problem here.
The goal is to check server-side (storage) snapshot for unique device data every time my app is saving or loading and then save processed, up-to-date data to storage.
For example, I’m trying to implement next simple logics:
**Device A** saves unique ID to snapshot (and creates it).
**Device B** is trying to load data from snapshot, compares own ID with snapshot’s one and finds out that data is not equal. So that device B writes own ID to snapshot and saves it.
**Device B** gets up-to-date (own) data on load. 
On that moment strange things appear.
Let’s try to load snapshot with **device A**.
Obtained on open snapshot has data from device B, so that device A is trying to save own ID in its turn.
It commits modified snapshot and gets STATUS_OK.
**Device B** sees nothing new on load.
Let’s try to load snapshot with **device A** once again.
Obtained on open snapshot has updated metadata but old (B) content!
Actual data is obtained only in 5-10 minutes.
Is it related to some kind of caching? 
What can I do to make it more reliable? 
Is it possible to know that snapshot isn’t REALLY applied for certain moment?
I really appreciate any help you can provide.

**Comment by claywilkinson** [comment]
Thanks for the detailed report.  Do you think you could capture logcat logs of when device "B" is loading and does not get the update and the subsequent loading on "A"?

**Comment by DummyCo** [comment]
Sorry for such long response. Finally I've managed to fix it. Seems like this behavior is strongly related to Android account synchronization settings and data usage politics. It was necessary to enable auto synchronization or manually synch AppData/Drive and consider mobile data usage settings for system and Drive application:

![screenshot_2016-04-07-20-24-30_publ](https://cloud.githubusercontent.com/assets/3989453/14360760/8a8ca928-fd00-11e5-9e88-ae719298f6e8.png)
![screenshot_2016-04-07-20-25-05_publ](https://cloud.githubusercontent.com/assets/3989453/14360761/8a8cfa7c-fd00-11e5-88a1-1dacb2618f9f.png)
![screenshot_2016-04-07-20-27-37_publ](https://cloud.githubusercontent.com/assets/3989453/14360762/8a921c8c-fd00-11e5-98d6-338b02adbc5b.png)

**Comment by mwgray** [comment]
Closing.
