### ISSUE TITLE
Google Play Music: Ads do not pause during calls

### ISSUE THREAD

**Issue by lucashtnguyen** [playgameservices/android-basic-samples#191]
Typical behavior when an incoming call is answered is to pause/mute Google Play Music. However, if a call is answered during an ad the ad does not seem to respect this behavior and continues to play over the call. 

Device details:
Nexus 5
Android build: 6.0.1 
Kernal v 3.4.0-g7717f76
Build: MMB29S
Google Play Music v 6.2.2224U.2493459

**Comment by claywilkinson** [comment]
Thanks for the feedback.  This repository is for the supporting the samples using Google Play Game Services, and not general support of applications.  To send your feedback, open Google Play Music, and from the menu select "Help & Feedback" and select "Send Feedback".

**Comment by lucashtnguyen** [comment]
@claywilkinson woops, sorry about that!
