### ISSUE TITLE
Runtime permissions not handled on Android 6.0.0

### ISSUE THREAD

**Issue by tobrun** [playgameservices/android-basic-samples#193]
Running the `TypeANumber` example crashes on Android Marshallow. In the logcat I can see a  SecurityException. This indicates that runtime permissions are not correctly implemented.

#### Steps to reproduce:
- Checkout this repo
- Import into Android Studio
- replace the required google play services keys
- deploy app on an Android 6.0.0 device
- app crashes with SecurityException

#### Expected behavior
Dialog is shown to select a Google account.

#### Relevant logs/screenshots
Don't have any at this time.

**Comment by claywilkinson** [comment]
Thanks for the report - we'll take a look. If you have a log you could share, that will help a lot.

**Comment by claywilkinson** [comment]
Please provide a log of the crash.  I built the samples again and they ran without issue.

**Comment by claywilkinson** [comment]
Closing this one. I believe it it resolved.  Please open another issue if that is not the case.
