### ISSUE TITLE
35 resources missing - How to run this sample?

### ISSUE THREAD

**Issue by AndroidPICO** [playgameservices/android-basic-samples#198]
Hello,

35 resources missing

example 

C:\Users\AndroidPICO\Desktop\android-basic-samples-master\android-basic-samples-master\BasicSamples\libraries\BaseGameUtils\build\intermediates\exploded-aar\com.android.support\appcompat-v7\23.2.0\res\drawable\abc_textfield_search_material.xml

Error:(18, 87) No resource found that matches the given name (at 'drawable' with value '@drawable/abc_textfield_search_activated_mtrl_alpha').
Error:(19, 89) No resource found that matches the given name (at 'drawable' with value '@drawable/abc_textfield_search_activated_mtrl_alpha').

Any tips?

**Comment by AndroidPICO** [comment]
Is that real, that i have to copy every resources from build to src?

**Comment by ianhanniballake** [comment]
No, you should probably just update the 23.2.0 to 23.2.1 (23.2.0 uses support vector drawables and requires [specific build.gradle modifications](http://android-developers.blogspot.com/2016/02/android-support-library-232.html) - [23.2.1](https://plus.google.com/+AndroidDevelopers/posts/BZgzpAqkd8G) reverted that as it broke people who didn't read the update notice.
