### ISSUE TITLE
uses-sdk:minSdkVersion 1 cannot be smaller than version 7 declared in library [com.android.support:appcompat-v7:23.2.0]

### ISSUE THREAD

**Issue by mirokuxy** [playgameservices/android-basic-samples#199]
I'm following this Google Play Games Services tutorial: https://developers.google.com/games/services/android/quickstart#before_you_begin

I've followed every single step in this tutorial, but when I tried to build the "Type-A-Number" package,
it showed me:

```
Error:Execution failed for task ':libraries:BaseGameUtils:processDebugAndroidTestManifest'.
> java.lang.RuntimeException: Manifest merger failed : uses-sdk:minSdkVersion 1 cannot be smaller than version 7 declared in library [com.android.support:appcompat-v7:23.2.0] /Users/sean/Progs/android-basic-samples/BasicSamples/libraries/BaseGameUtils/build/intermediates/exploded-aar/com.android.support/appcompat-v7/23.2.0/AndroidManifest.xml
    Suggestion: use tools:overrideLibrary="android.support.v7.appcompat" to force usage
```

Can anyone tell me how to solve it?

**Comment by AndroidPICO** [comment]
File->Project Structure and set there for every module min SDK version in Flavors section.

**Comment by allenxuan** [comment]
After applying  AndroidPICO's method, another error appears as "Error:(24, 0) Gradle DSL method not found: 'compile()'
Possible causes:
The project 'BasicSamples' may be using a version of Gradle that does not contain the method.
"

**Comment by mirokuxy** [comment]
@allenxuan  I met the same problem. And I solved it by adding "minSdkVersion" to the build.gradle file for this module. The default build.gradle file does not contain "minSdkVersion", and Andoird studio will automatically set "minSdkVersion" to 0 when "minSdkVersion" is not set, which will cause the error stated above.

**Comment by tboyce1** [comment]
@allenxuan did you ever solve the second error you were seeing? I'm having the same problems.

**Comment by tboyce1** [comment]
Actually, for whatever reason, the build.gradle file was downloaded with all of the "compile" statements on the same line. Splitting each of them onto their own line fixed the issue for me.

**Comment by mwgray** [comment]
The latest version has deprecated BaseGameUtils, so this should no longer be an issue.

**Comment by evilGenious** [comment]
You have to add the minSdkVersion to your build.gradle.

Otherwise, gradle uses the default value = 1.
You are using a library with minSdk=7, then you can't use minSdk
