### ISSUE TITLE
Google Play services problem with SGH-T999V (Galaxy S3 phone)

### ISSUE THREAD

**Issue by Wagnard** [playgameservices/android-basic-samples#200]
Hi,
First excuse my English, it is not my first language.
Since the latest update of "Google Play Services 8.7.03(2645110-036)" on my phone, everything apps that used it.  have connection problem.
Google + for example is constantly saying that it is impossible to load the data and that I must check connection and try again later.
If I keep refreshing, it will usually work after 3-4 try.
I have already rule out the connection problem as it happen on both WIFI and 4G connection. I have reset the phone to factory default and reinstall everything and it still happens.

On top of that, my wife have the same phone and same problem since the update on the beginning of march.

Other affected apps, are Google Photos,  The Gallery app that came with my phone (sync with google photo)
Gmail now often fail to sync the new mail. I see there was an error synchronizing and must force it again...
I hope you guys can help.

**Comment by claywilkinson** [comment]
@Wagnard - This site is for supporting developers writing games for Android.  I'd suggest submitting your feedback via the "Send Feedback" menu item in the applications you are referring to.
