### ISSUE TITLE
Error with BaseGameUtils.resolveConnectionFailure

### ISSUE THREAD

**Issue by hidrodf** [playgameservices/android-basic-samples#204]
Anyone knows something about this?

![sin titulo](https://cloud.githubusercontent.com/assets/17657543/15622772/add20e94-246c-11e6-8a7e-03c0491a9295.png)

**Comment by mallenusc** [comment]
Your passing a String variable where it now requires an int.  Instead of hard coding your error message.  Put the error message in the String resource file and use the ID if the String instead.
Example from Google Developer:

        if (!BaseGameUtils.resolveConnectionFailure(this,
                mGoogleApiClient, connectionResult,
                RC_SIGN_IN, R.string.signin_other_error)) {
            mResolvingConnectionFailure = false;
        }

**Comment by mwgray** [comment]
The latest version has deprecated BaseGameUtils, so this should no longer be an issue.
