### ISSUE TITLE
Unusual Behavior When Locking Device During Google Play Splash Screen

### ISSUE THREAD

**Issue by johntevans** [playgameservices/android-basic-samples#206]
**Steps to Reproduce**
1. Initiate Google Play Sign-In
2. While the Google Play splash screen is Visible, lock the device
3. Unlock the device

**Observed Result**
The Google Play splash is visible, but the device's layout has been changed from landscape mod to portrait mode. Furthermore, tapping on the screen dismisses the splash image, but doesn't allow to player to progress through the Google Play sign-in flow.

I've attached a video demonstrating the reproduction steps and the result, as well as a log from when the bug happened, and a log from when the player successfully completed Google Play sign-in. 

After searching for other bugs, I believe that this issue could possibly be related https://github.com/playgameservices/play-games-plugin-for-unity/issues/1220

[google-play-bug-video.zip](https://github.com/playgameservices/android-basic-samples/files/330693/google-play-bug-video.zip)
[google-play-success.txt](https://github.com/playgameservices/android-basic-samples/files/330734/google-play-success.txt)
[google-play-bug.txt](https://github.com/playgameservices/android-basic-samples/files/330735/google-play-bug.txt)

**Comment by simonebg73** [comment]
Did you manage to find a fix or workaround for this?

**Comment by sau4urs** [comment]
I am also facing the same issue. Has anyone found any solution or workaround for this?

**Comment by mwgray** [comment]
Looks related to #217, closing as a duplicate.
