### ISSUE TITLE
No Connection Error!!

### ISSUE THREAD

**Issue by MobiPerson410** [playgameservices/android-basic-samples#208]
I installed Google Play Games and updated Google Play Services, but I can't log in to my Google Play Games account it says no internet connection, even if you use a WI-FI network. The other Google apps works perfectly, only Play Games that errors. Please I cannot continue my Games Cloud save data. It happens when I installed this two apps after I factory reset my android device.

**Comment by mwgray** [comment]
I'm not sure how to reproduce the problem and if relates to the java samples.  If you are still encountering this issue, feel free to open up a new issue with more information.
