### ISSUE TITLE
Unlock Achievements

### ISSUE THREAD

**Issue by GauravCreed** [playgameservices/android-basic-samples#214]
Hi @hak 

i just download BaseGameUtils reside android-basic-samples for the android achievements, and then i create AchievementsActivity.JAVA to shows users Achievements, it will work fine but what i want..

I want to unlock Achievements from my other different activities. what i have try ... 

`new BaseGameActivity() {
            @Override
            public void onSignInFailed() {

```
        }

        @Override
        public void onSignInSucceeded() {
```

// My Achievements code
            }
        }` 

in that above code i can't get getApiClient() that's why app is crash. then how can i unlock my diff Achievements in diff activities,is it possible...? then how ? please help me...

thanks.

**Comment by mwgray** [comment]
BaseGameUtils has been deprecated with the latest release.  You can check out the Type A Number sample to see how to use the new API and achievements.  If you still encounter issues, feel free to open a new issue.
