### ISSUE TITLE
Could not find property 'build_tools_version'

### ISSUE THREAD

**Issue by elile** [playgameservices/android-basic-samples#218]
Error:(44, 0) Could not find property 'build_tools_version' on com.android.build.gradle.LibraryExtension_Decorated@48c36baf.

**Comment by secret-dave** [comment]
Error:(44, 0) Could not find property 'build_tools_version' on com.android.build.gradle.LibraryExtension_Decorated@5ce0dec3.

```
apply plugin: 'com.android.library'

buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:1.3.1'
    }
}

dependencies {
    // Set defaults so that BaseGameUtils can be used outside of BasicSamples
    if (!project.hasProperty('appcompat_library_version')) {
        ext.appcompat_library_version = '20.0.+'
    }
    if (!project.hasProperty('support_library_version')) {
        ext.support_library_version = '20.0.+'
    }
    if (!project.hasProperty('gms_library_version')) {
        ext.gms_library_version = '8.4.0'
    }

    compile "com.android.support:appcompat-v7:${appcompat_library_version}"
    compile "com.android.support:support-v4:${support_library_version}"
    compile "com.google.android.gms:play-services-games:${gms_library_version}"
    compile "com.google.android.gms:play-services-plus:${gms_library_version}"
}

android {
    // Set defaults so that BaseGameUtils can be used outside of BasicSamples
    if (!project.hasProperty('android_compile_version')) {
        ext.android_compile_version = 23
    }
    if (!project.hasProperty('android_min_version')) {
        ext.android_min_version = 15
    }
    if (!project.hasProperty('android_version')) {
        ext.build_tools_version = "23.0.2"
    }

    compileSdkVersion android_compile_version
    buildToolsVersion build_tools_version

    defaultConfig {
        minSdkVersion android_min_version
        targetSdkVersion android_compile_version
    }
}


```
Changed the buildscript but again the same error.
```
buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.0'
    }
}
```
Error:(44, 0) Could not find property 'build_tools_version' on com.android.build.gradle.LibraryExtension_Decorated@6f78d566.

**Comment by Valthorn** [comment]
Error:(44, 0) Could not find property 'build_tools_version' on com.android.build.gradle.LibraryExtension_Decorated@20955e6.

Getting Same Error here. Anybody have a solution for this?

**Comment by phunni** [comment]
Same error here:

Could not find property 'build_tools_version' on com.android.build.gradle.LibraryExtension_Decorated@32680579.

**Comment by fisherben** [comment]
Error:(44, 0) Could not find property 'build_tools_version' on com.android.build.gradle.LibraryExtension_Decorated@28a49dc1.
<a href="openFile:C:\Users\Ben\AndroidStudioProjects\android-basic-samples-master\BasicSamples\libraries\BaseGameUtils\build.gradle"></a>

**Comment by mwgray** [comment]
This should not be an issue with latest.  If you are still encountering it, feel free to reopen.
