### ISSUE TITLE
No way of retrieving the url of a video recorded 

### ISSUE THREAD

**Issue by 00christian00** [playgameservices/android-basic-samples#220]
Hello,
Currently the play services recording api has no means to retrieve the url of the shared video.
We plan to incentivize users to record their play but it is mandatory that we can :
1-Get confirmation of the share.
2-Get the actual url of the share so that we can create a sort of leaderboard with the recording of the best players.

Please add such feature to the service.

Thanks
Regards
Chris

**Comment by claywilkinson** [comment]
Thanks for the feedback!

**Comment by claywilkinson** [comment]
I confirmed that there is no way to get the URL of the shared video back.  One idea is to also integrate the [YouTube API](https://developers.google.com/youtube/v3/getting-started) and search for the video to get a playable link?

**Comment by 00christian00** [comment]
And what would you search? You don't have any data at all on the shared video.

**Comment by claywilkinson** [comment]
Good point. I guess you could prompt the player for the title or something in order to get the reward.  Alternatively, the video is stored locally on the device and you upload it using the API and you would know more about the metadata (but that does lessen the value of the recording API....).

**Comment by 00christian00** [comment]
How does it currently upload the video? Doesn't it use youtube api already?
If it does isn't enough to implement the callback to receive the uploaded video details?

**Comment by williambyrd** [comment]
Thanks

**Comment by 00christian00** [comment]
So, go anything cooking on this issue for next versions?

**Comment by 00christian00** [comment]
So has there been any progress on this?

**Comment by 00christian00** [comment]
Any feedback would be welcome, it has been more than 1 year without answers

**Comment by 00christian00** [comment]
Has this feature been abandoned?
