### ISSUE TITLE
Usage of deprecated code in GameHelper.Java

### ISSUE THREAD

**Issue by idanlv** [playgameservices/android-basic-samples#222]
Line 280 : builder.addScope(Plus.SCOPE_PLUS_LOGIN);
Line 531 : Plus.AccountApi.clearDefaultAccount(mGoogleApiClient);

**Comment by claywilkinson** [comment]
Thanks! - we'll update the samples soon.

**Comment by mwgray** [comment]
GameHelper.java is deprecated, shouldn't be an issue anymore.
