### ISSUE TITLE
Games.Players.loadConnectedPlayers returns 0 players

### ISSUE THREAD

**Issue by eyenie** [playgameservices/android-basic-samples#224]
Hello I have an issue with loadConnectedPlayers, It can return 20+ connected players several times, but eventually it starts returning 0 players while status is still STATUS_OK.
I can reproduce it for all my accounts, and it really hard to make it start returning connected players again. Sometimes removing google account and clearing cache for Google Games helps.
Setting second parameter in loadConnectedPlayers to "true" doesn't help.
Here is the code:
```
@Override
public void loadFriends() {
	Log.d(TAG, "GameCenter - loadFriends()");
	if (isSignedIn()) {
		Games.Players.loadConnectedPlayers(getApiClient(),false).setResultCallback(new ResultCallback<Players.LoadPlayersResult>() {
			@Override
			public void onResult(@NonNull Players.LoadPlayersResult loadPlayersResult) {
				Log.d(TAG, "GameCenter - loadFriends(): " + loadPlayersResult.getStatus());
				if (loadPlayersResult.getStatus().isSuccess()) {
					for (Player player : loadPlayersResult.getPlayers()) {
						Log.d(TAG, "GameCenter - loadFriends() add player:" + player.getPlayerId());
					}
				} 
			}
		});
	}
}
```

**Comment by claywilkinson** [comment]
The list returned from loadConnectedPlayers will be empty when using the "Games Lite"  version of Play Game Services.  This started rolling out in February 2016.  The "standard" UIs for inviting players will continue to work for some time, but will soon also be empty.  You can read more about the changes here:
https://android-developers.googleblog.com/2016/12/games-authentication-adopting-google.html
