### ISSUE TITLE
Top nav gets overlapped

### ISSUE THREAD

**Issue by imashankar** [playgameservices/android-basic-samples#226]
Move to https://play.google.com/store/apps/dev?id=6720847872553662727&hl=en_GB

scroll the page till the "arrow icon" reaches the top nav. You can see that icon is overlapping the nav.

Tried the following and looks like it works. But I am not sure where all .cover for featured apps is used. There should be a reason why its z-index is 2002.

.action-bar-container.sticky .action-bar-inner {
    position: fixed;
    top: 0;
    **z-index: 1052;**
}
.developer-featured-apps-content .cover {
    height: 64px;
    margin: 0;
    width: 64px;
    **z-index: 100;**
}

<img width="1123" alt="screen shot 2016-11-16 at 7 20 57 pm" src="https://cloud.githubusercontent.com/assets/6292351/20349820/1bf466ea-ac32-11e6-8796-25aef4c6d011.png">

**Comment by claywilkinson** [comment]
You should post this type of question to the play console help directly.  This project is focused on the use of  Google Play Game Services SDK in the game.
