### ISSUE TITLE
Games.Quests.load() takes 5 to 8 seconds to load user data

### ISSUE THREAD

**Issue by ashtrisk** [playgameservices/android-basic-samples#229]
See Code Snippet Below : 

```
PendingResult<Quests.LoadQuestsResult> loadQuest = Games.Quests.load(activity.getGoogleApiClient(),
        Quests.SELECT_ALL_QUESTS, Quests.SORT_ORDER_ENDING_SOON_FIRST, true);

loadQuest.setResultCallback(new ResultCallback<Quests.LoadQuestsResult>() {
        @Override
        public void onResult(@NonNull Quests.LoadQuestsResult loadQuestsResult) {
                // Gets called after around 5 to 8 seconds.
        }
});

```

Even on a 3G network and correct sign In the request callback gets called after approximately 5 to 8 seconds of load() call.

Note : I don't know whether this is the right platform for posting such an issue but I couldn't found any other platform. Please help in any way possible.

**Comment by mwgray** [comment]
Quests have been deprecated, see the announcement [here](https://android-developers.googleblog.com/2017/04/focusing-our-google-play-games-services.html).
