### ISSUE TITLE
AccomplishmentsOutbox class

### ISSUE THREAD

**Issue by kursadaydin** [playgameservices/android-basic-samples#230]
Can you give an explanation of AccomplishmentsOutbox class' saveLocal and loadLocal methods'?
What may i do for saving unless user sign in

**Comment by claywilkinson** [comment]
What code are you referring to for AccomplishmentsOutbox?  I don't think that is part of Play Game Services? https://developers.google.com/games/services/

**Comment by mwgray** [comment]
The purpose of AccomplishmentsOutbox is to temporarily store the player's game state until the user signs in.  Once the sign in occurs, the pending achievements are updated and sent.

The save/loadLocal methods were deprecated recently, but the intent was to save and load the data to the device in case the application was destroyed.

Closing for now.
