### ISSUE TITLE
Adding BaseGameUtils to LibGDX: Library has broken classes paths error

### ISSUE THREAD

**Issue by chandujr** [playgameservices/android-basic-samples#236]
I'm trying to implement Play Services in my Libgdx game. Following [this tutorial](https://github.com/libgdx/libgdx/wiki/Google-Play-Game-Services-in-LibGDX), I downloaded the `BaseGameUtils` library from here and added it to my project.

When I open the `BaseGameUtils.java` file, I have errors in the import statement:

`import com.google.android.gms.common.ConnectionResult; // cannot resolve symbol 'common'`

When I view the Project Structure window, there are errors listed:

![Problems tab in Project Structure](https://cloud.githubusercontent.com/assets/14921501/21585297/6affa33c-d0e3-11e6-901e-0cee125469f2.JPG)

The changes I made after adding the `BaseGameUtils` library to the project:
* Added `'BaseGameUtils'` to the project settings.gradle file.
* Added `compile project(":BaseGameUtils")` as the android dependency in root gradle.
* Tried with different versions of Android Support libs, GMS libs and Gradle plugins.

**Root gradle file:** http://pastebin.com/in2MmYMM
**Android gradle file:** http://pastebin.com/ya85gGs4
**BaseGameUtils gradle file:** http://pastebin.com/0iyz2j12

**Comment by claywilkinson** [comment]
Can you build the samples in this repository successfully? Did you try to remove BaseGamesUtils from your project and add the play-services-* dependencies directly to your project? There is not much in BaseGameUtils that is still useful to a new game, it is mostly there as reference.

**Comment by chandujr** [comment]
@claywilkinson Thank you but this issue got solved when I used the 64-bit IDEA. I was using the 32-bit version. I'm not really sure of the underlying problem, probably JRE compatibility issues?

Anyway, the library got downloaded without errors when working with the 64-bit IDE. (`idea64.exe` in the `/bin/` directory).

**Comment by claywilkinson** [comment]
Thanks for the response & I am glad you got it working.
