### ISSUE TITLE
v.0.9.36 Leaderboard Load Score Bug

### ISSUE THREAD

**Issue by VadimTikhonyuk** [playgameservices/android-basic-samples#239]
Hi, there
I have an bug with leaderboards.
When I download user score by code, it return me score, which I report in first  time. But when I open LeaderboardUI I can see correct score.

If loading doesent work, i will be get 0 or error, but no, they return for me first score.

![ce2xp9odh2e](https://cloud.githubusercontent.com/assets/13260375/22605818/3ab4d568-ea5a-11e6-9cd8-dbd42821eb34.jpg)
![6a2lwdzds34](https://cloud.githubusercontent.com/assets/13260375/22605820/3ab7180a-ea5a-11e6-8dd1-8be59bf11136.jpg)
![screenshot_2017-02-03-19-06-02](https://cloud.githubusercontent.com/assets/13260375/22605821/3ab77854-ea5a-11e6-8656-ad45f71ff5be.png)
![screenshot_2017-02-03-19-05-47](https://cloud.githubusercontent.com/assets/13260375/22605819/3ab5e4ee-ea5a-11e6-94cd-dc19033cf44c.png)

**Comment by mwgray** [comment]
This doesn't look directly related to the samples.  If you find this is still an issue with the latest samples, feel free to open a new issue and provide more information.  Closing for now.
