### ISSUE TITLE
[play-services] AdvertisingIdClient.getAdvertisingIdInfo new nullpointer exception introduced in v9.8

### ISSUE THREAD

**Issue by fbbarros** [playgameservices/android-basic-samples#240]
We recently updated play-services to 10.0.1 and we've been since encountering an issue where AdvertisingIdClient.getAdvertisingIdInfo() can return null.

The [documentation](https://developers.google.com/android/reference/com/google/android/gms/ads/identifier/AdvertisingIdClient#getAdvertisingIdInfo(android.content.Context)) is pretty clear on the valid return types and throwable exceptions making null a non-valid return type by design.

After trying out all earlier versions down to 9.6+ we were able to determine the issue to have been introduced on 9.8+.

Although we can easily fix this on our project, the same can not be said for third party sdk's, most notably for ads and tracking related services.

If this is a new design choice, then the documentation should be updated, and sdk users should be prompted to the change at the very least in the release notes.
Otherwise it should be logged as bug. The issue has been so far documented by several users on stackoverflow but to this date no issue/bug seems to have been logged and the problem seems to be thus far ignored.

Cheers,
Fernando Barros

**Comment by mwgray** [comment]
This doesn't look directly related to the samples for Play Game Services.  If you find this is still an issue with the latest samples, feel free to open a new issue and provide more information.  Closing for now.
