### ISSUE TITLE
Submit Button is not visible on Android Set UP

### ISSUE THREAD

**Issue by TimLCooley** [playgameservices/android-basic-samples#241]
I am in the process of setting up Android Google Play.  You can see from the screenshot I took that there is no way to scroll down and the Submit and Cancel buttons don't show up. Is there something I need to change to make this possible?

![image](https://cloud.githubusercontent.com/assets/2152153/23008422/d2120676-f3cc-11e6-8678-b5ebadd0e2e6.png)

**Comment by mwgray** [comment]
This looks like it is for the [Unity plugin](https://github.com/playgameservices/play-games-plugin-for-unity), this repo is for java samples, so closing for now.  

If you are still encountering this issue, feel free to open an issue in the Unity plugin repo.
