### ISSUE TITLE
loadInvitablePlayers() alternative?

### ISSUE THREAD

**Issue by fcouceiro** [playgameservices/android-basic-samples#242]
Hi.

I've read that with the new updates this functionality will be deprecated. ([here](https://android-developers.googleblog.com/2016/12/games-authentication-adopting-google.html)). How would one implement this behavior from now on?

**Comment by mwgray** [comment]
While that specific function is deprecated, you can look at the Button Clicker sample for an example on how to invite any players that are currently playing.
