### ISSUE TITLE
Cannot detect login info even after logged in!

### ISSUE THREAD

**Issue by a159nish** [playgameservices/android-basic-samples#246]
When i start my app it shows that it is connecting to the Google Play Game in green animation and then shows the message of failed to sign in. I might need some help please!

**Comment by claywilkinson** [comment]
Can you share the log of when you are signing in?  Usually there is some indicator of the problem.
Things to check:
1. The applicationId in your build.gradle matches the packageId in the linked Android application in the Play Console.
2. The SHA1 of the key you used to sign your application also matches.
3. The appId in your AndroidManifest.xml (or in a string resource file) matches the game ID the applications are linked to.

**Comment by mwgray** [comment]
Closing due to lack of response.  @a159nish, if you are still encountering issues, feel free to re-open with more information.
