### ISSUE TITLE
Google Play Games and the emulator

### ISSUE THREAD

**Issue by stolk** [playgameservices/android-basic-samples#251]
Is Google Play Games login supposed to work in the emulator?
I can log in on hardware devices.

But on the Android Emulator - NEXUS 5 - API 25, I get:

```
07-01 22:03:22.652 5858-5858/com.steenriver.buggy V/GamesNativeSDK: Play Games callback indicates connection failure.
07-01 22:03:22.652 5858-6124/com.steenriver.buggy I/GamesNativeSDK: UI interaction required to connect to Google Play.
```

**Comment by claywilkinson** [comment]
It does not work in the emulator because the Play Games App is not part of the emulator image.
You'll need to use an emulator configuration that includes the Play Store - then you'll be able to install the required apps.

**Comment by stolk** [comment]
Thanks, but my emulator has Google Play Games app running on it.

https://lh3.googleusercontent.com/-1BRH9SrE-G0/WV2thfgOaBI/AAAAAAAAElA/S3icTARj4n4CXbX-lRbKRTtet5YZbygXgCL0BGAs/w519-d-h923-p/emu.png

**Comment by pvella** [comment]
Be careful with the emulator.  I am getting some strange crashes to do with Static variables being handled differently.  Physical devices is the best way to test.

**Comment by mwgray** [comment]
Closing, seems like it is resolved
