### ISSUE TITLE
BaseGameUtils forces old version of Build Tools.

### ISSUE THREAD

**Issue by stolk** [playgameservices/android-basic-samples#252]
The BaseGameUtils build.gradle is using an old build tools version: 23

android-basic-samples/BasicSamples/libraries/BaseGameUtils/build.gradle

**buildToolsVersion "23.0.2"**

Where as the samples use a newer (but also superseded) version: 25

Both should probably be replaced with the latest build tools version: 26.
But whatever the version, it should not differ between the sample itself and the library.

**Comment by mwgray** [comment]
The latest version has deprecated BaseGameUtils, so this should no longer be an issue.
