### ISSUE TITLE
Samples not using the latest Google Play Services.

### ISSUE THREAD

**Issue by stolk** [playgameservices/android-basic-samples#253]
The build.gradle of the Samples uses an old Google Play Services: version 10.0.1

Whereas 11.0.2 is available:

![image](https://user-images.githubusercontent.com/455280/28280170-b84d2ef0-6ad7-11e7-9027-bb4d24e167a9.png)

**Comment by mwgray** [comment]
The latest version uses version 11.6.2, closing!
