### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by lzubiaur** [playgameservices/android-basic-samples#257]
Commit [3fd5510](https://github.com/playgameservices/android-basic-samples/commit/3fd5510db461f2a6b7728fb4dc8c54e477fc6771#diff-182bae0a69bb9e82be251d4cfcc0bff2) changed param `fallbackErrorMessage` to int but examples still pass a String.

**Comment by mwgray** [comment]
The latest version has deprecated BaseGameUtils, so this should no longer be an issue.
