### ISSUE TITLE
Android Saved Game State

### ISSUE THREAD

**Issue by brianasu** [playgameservices/android-basic-samples#259]
In the android-samples SavedGame I noticed the GoogleAPIClient does not addAPI(Drive.API) is that required?

This is relevant to me because I'm having an issue where it is asking me a Age and "Share Google+ profile" permission is requested if I addApi(Drive.API)

**Comment by mwgray** [comment]
The latest samples have deprecated the save SavedGame, you can look to the CollectAllTheStars sample for snapshots usage.

In the latest API, you want to use the scopes system to add the Drive.SCOPE_APPFOLDER when signing in.  You can look at the [docs](https://developers.google.com/games/services/android/savedgames#specifying_the_drive_scope) for more information.
