### ISSUE TITLE
Games.TurnBasedMultiplayer and other package depreciated

### ISSUE THREAD

**Issue by pvella** [playgameservices/android-basic-samples#263]
I noticed that most of the BaseGameUtils packages are now depreciated.  Will the SkeletonTBMP and other examples be update to show how we use the new Games packages?

**Comment by mwgray** [comment]
Yes, you are correct!  The BaseGameUtils library, along with some other samples, have been deprecated.  The current set of samples, which includes SkeletonTbmp, will demonstrate the correct usage of the new API Client.
