### ISSUE TITLE
ButtonClicker bugs

### ISSUE THREAD

**Issue by denri11** [playgameservices/android-basic-samples#264]
**1)** In the multiplayer game mode after connection established there is no way to go to screen_game scene. That’s because when onConnected() method called then always switchToMainScreen() method called. Default Waiting room UI calls onPause() on Activity, and in onResume() always called signInSilently() with this sequence of calls:
 
showWaitingRoom(room) -> onPause() -> startGame(true) -> switchToScreen(R.id.screen_game) -> onResume() -> signInSilently() -> onConnected() -> switchToMainScreen()

**2)** In onConnected() method
Multiplayer.EXTRA_TURN_BASED_MATCH should be replaced on Multiplayer.EXTRA_INVITATION

**Comment by mwgray** [comment]
Good catch!  Fixes incoming...

**Comment by mwgray** [comment]
Hi @denri11, the latest code should fix the issue.  I added some extra protections in there too.  If you find any other oddities, feel free to re-open, or even submit your on PR!

**Comment by denri11** [comment]
Hi. 
I don't know who else to turn to. There was a global issue with Google Play games services. Since March 28, about half of users do not work online multiplayer. I get a lot of emails from users. The problem is really global. With her faced many developers. This may be due to the Google services update on users ' devices. This may be a regional problem. I am in Minsk (Belarus), however through vpn Germany at me earned. I apologize for my English.

onRoomCreated(int statusCode, Room room) method throws an error:
statusCode 4

Other references describing the problem:
https://productforums.google.com/forum/?utm_medium=email&utm_source=footer#!msg/play/dP3BHrI1vN4/CB_pwgHlCQAJ
https://stackoverflow.com/questions/49587007/google-play-service-real-time-multiplayer-is-broken
https://github.com/playgameservices/play-games-plugin-for-unity/issues/2163

Thanks.

**Comment by alexanderkrupenkov** [comment]
Hello, I have the same problem with multiplayer. Many users notify me about problems with multiplayer. Usually it's from Russian.
