### ISSUE TITLE
No way of detecting when a RTM player disconnects.

### ISSUE THREAD

**Issue by RubiconDev** [playgameservices/android-basic-samples#267]
I'm using v 2.1 of the cpp gpg SDK. 

My app runs perfectly, sending and receiving data between player A and B.

If B switches his WIFI off, there is no callback to let A know that he has left the game. 

OnP2PDisconnected() isn't triggered.
OnRoomStatusChanged() isn't triggered.
OnParticipantStatusChanged isn't triggered.

Surely this isn't correct? I don't really want to have to add keep-alive ping packets to my game when it seems like there is facility already available using these callbacks.

Why don't they work?

BTW:I tried updating to v3.0 of the SDK, this causes masses of linker errors.

Regards,

Steve.

**Comment by mwgray** [comment]
Hi @RubiconDev,

This repo is for the java samples, you should try asking in the [cpp repo](https://github.com/playgameservices/cpp-android-basic-samples).

Closing for now.
