### ISSUE TITLE
Can't find BasicSamples folder

### ISSUE THREAD

**Issue by jaynguyeninf** [playgameservices/android-basic-samples#268]
Hi. Where's this folder located at?

**Comment by mwgray** [comment]
BasicSamples has been deprecated; all the files have been pulled to the root.

**Comment by jaynguyeninf** [comment]
So for these codes, are they a project on their own or I need to add them to my existing project?

**Comment by mwgray** [comment]
If you open the root folder of the repo with Android Studio it will have all the projects in one.  More details in the readme [here](https://github.com/playgameservices/android-basic-samples#building-using-android-studio).
