### ISSUE TITLE
No Src/GameHelper

### ISSUE THREAD

**Issue by jaynguyeninf** [playgameservices/android-basic-samples#269]
Hi. Sorry for the noob question, but I don't see any libgdx source code in the repository, so where is the GameHelper class located at?

**Comment by mwgray** [comment]
Hi @jaynguyeninf, GameHelper was deprecated and removed.  

You mentioned libgdx code, which is unrelated to this repository; what are you looking for?

**Comment by jaynguyeninf** [comment]
@mwgray Hi. I didn't know this is deprecated. I was looking for a lib that I can add Google play games services into my libgdx project.

**Comment by mwgray** [comment]
Ah I see.  The nature of this repo changed a bit over the years.  You can still find samples of interacting with GPGS, but they are each in a specific sample.  You can still grab the related code and use it in your own project.

Closing for now.
