### ISSUE TITLE
Google Play Games plugin for Unity connecting bug

### ISSUE THREAD

**Issue by liranjulia** [playgameservices/android-basic-samples#303]
Hi there,

We have reported this bug directly in the repository (along with numerous other people), but nothing has been done about it. In our game Idle Plague, players have complained that google play games tries to connect unsuccessfully. The circle just continues animating forever and can't connect. Some players can't even enter the game, others can using the back button. It mostly happens with Android 10 phones. We are using the plugin that is supported by Google and recommended on your page. We have tried to find solutions for this with no success. We need a solution for this, because both Google and our company are losing money as a result of players not being able to enter the game.

Kind regards,

**Comment by ozdemir08** [comment]
Hey @liranjulia. The team is looking into the issue. Any information you provide us could be helpful for our investigations. Also could you point me to the issue in the plugin repository?

**Comment by liranjulia** [comment]
Hi there, thanks for your quick reply. Unfortunately we haven't been able
to reproduce this bug, so we don't have logs for it, but a few dozen
players have complained about this. They say that while trying to connect
to Google Play the circle circles forever, no matter how long they wait, so
they are unable to enter the game. Most of them have Android 10, some had
9. These look like similar issues in the plugin repository:

https://github.com/playgameservices/play-games-plugin-for-unity/issues/2142

https://github.com/playgameservices/play-games-plugin-for-unity/issues/2107

https://github.com/playgameservices/play-games-plugin-for-unity/issues/2042

I thought my partner posted an issue, but he didn't because there were so
many open already with no reply...

Thanks,

*Liran Julia Grunhaus*
Co-Founder, Graphic & Game Design

liranjulia@mooistudios.com
https://mooistudios.com/
https://twitter.com/mooistudios
https://www.facebook.com/mooistudios/

**Comment by ozdemir08** [comment]
They look quite outdated, so feel free to create a new one. 

We have many open issues but we have started addressing them starting from the recent ones. It will take time to look at the issues opened in 2018. Closing this issue as this is not about Android samples.

**Comment by liranjulia** [comment]
OK, just did, would appreciate it if someone looked at it
*Liran Julia Grunhaus*
Co-Founder, Graphic & Game Design

liranjulia@mooistudios.com
https://mooistudios.com/
https://twitter.com/mooistudios
https://www.facebook.com/mooistudios/
