### ISSUE TITLE
Cannot use snapshots without enabling the 'Saved Game' feature in the Play console

### ISSUE THREAD

**Issue by ominfowave** [playgameservices/android-basic-samples#321]
After setting everything as per the documents, I am always getting `Cannot use snapshots without enabling the 'Saved Game' feature in the Play console`  error when i try to open a snapshot.

Third step of 'Set up Play Games Services' on console always stays unchecked even tho i have added id and metadata in Manifest.
Setting screen: https://ibb.co/x2r245C

I have also enabled the 'Saved Game' option in Configurations screen.

**Comment by smile616** [comment]
@ominfowave 
have you followed https://developers.google.com/games/services/console/configuring#enabling_saved_games ?

**Comment by smile616** [comment]
please reopen if you followed the suggestion from comment above and it didn't resolved the issue.
