### ISSUE TITLE
sign in popup closes app

### ISSUE THREAD

**Issue by chitgoks** [playgameservices/android-basic-samples#50]
hi. just want to ask for confirmation if this is normal. the connecting to google play game popup sign in, in gamehelper shows but not on top of the calling activity

is this normal?

i tried to modify gamehelper setup() with extra View parameter so i could call buulder.setviewforpopups() but it doesnt work. the calling activity gets hidden while the sign in popup shows

**Comment by claywilkinson** [comment]
Closing old issues - please open a new issue if you have more questions.
