### ISSUE TITLE
Auto Match Criteria configuration Problem in BittonClicker Sample 

### ISSUE THREAD

**Issue by adnan78692** [playgameservices/android-basic-samples#9]
I changed auto-match criteria configuration as per my requirement

void startQuickGame() {
final int MIN_OPPONENTS = 1, MAX_OPPONENTS = 3;
   Bundle autoMatchCriteria = RoomConfig.createAutoMatchCriteria(MIN_OPPONENTS,
           MAX_OPPONENTS, 0);
   RoomConfig.Builder rtmConfigBuilder = RoomConfig.builder(this);
   rtmConfigBuilder.setMessageReceivedListener(this);
   rtmConfigBuilder.setAutoMatchCriteria(autoMatchCriteria);
   rtmConfigBuilder.setRoomStatusUpdateListener(this);

   getGamesClient().createRoom(rtmConfigBuilder.build());
}

but game still starts after 1(one) opponent (as set MIN_OPPONENT=1) . onRoomConnected() callback is called right after 1 opponent  and did not wait for further opponents (as we  set in MAX_OPPONETS.=3). 

i also tried with my own waiting room UI and add a time delay. after that delay game will starts with available opponents within min and max opponent limit. but this will never happen ...
i am confused. :(

**Comment by sapanaryal** [comment]
Almost two years and i have the same issue as adnan78692 has . Will anyone direct us with what went wrong or is it even possible to receive peers one by one .

**Comment by claywilkinson** [comment]
@sapanaryal  - There seems to be a couple actual issues discussed in this thread.  Seeing this is a closed issue and an old one at that - would you mind summarizing what issue you are having (ideally including logs and code snippets) on a new issue?  Thanks!

**Comment by sapanaryal** [comment]
hi claywilkinson , thanks for responding 
I will try to post about the issue in my own words but you may also refer to http://stackoverflow.com/questions/16775194/room-configuration-did-not-work-properly-in-google-real-time-multiplayer-service/16802177#16802177  -- here bruno has answered about the issue but has not responded to the comments which tells about the actual issue . 

SCENARIO::I want to create an auto match game ( no invited players here ) with minimum 1 player and maximum 5  players . So what I am expected to do here  is to create my own waiting room and wait for callback onPeersConnected. So as peers get connected i am expected to update my waiting room ui . Now i want to add play now button if players connected reaches 2 or more as players may agree to stop waiting for all 5 players and start the game immediately .     

PROBLEM::If i put min player as 1 and max player as 4 ,OnPeersConnected gets called after a player joins in as it should . And immediately onRoomConnected is called even though i want to wait for other players to join in . If i put min players to 4 and max players to 4 on room creation (which is the ideal thing to do), onpeersConnected  never gets called for single peers joining the room . its either 0 or 4 . So if there are two players waiting to be auto matched , I expect them to join the room and wait for other player or click on play now to start playing immediately . But automatching never takes place until 4 players are available .

 Room creation code 
final int MIN_OPPONENTS = 4, MAX_OPPONENTS = 4;
        Bundle autoMatchCriteria = RoomConfig.createAutoMatchCriteria(MIN_OPPONENTS,
                MAX_OPPONENTS, 0);
        RoomConfig.Builder rtmConfigBuilder = RoomConfig.builder(OnlineModeCoordinator.getInstance());
        rtmConfigBuilder.setMessageReceivedListener(OnlineModeCoordinator.getInstance());
        rtmConfigBuilder.setRoomStatusUpdateListener(OnlineModeCoordinator.getInstance());
        rtmConfigBuilder.setAutoMatchCriteria(autoMatchCriteria);
        keepScreenOn();
        Games.RealTimeMultiplayer.create(mGoogleApiClient, rtmConfigBuilder.build());	

I even tried to use google play games own waiting room 
Intent ii = Games.RealTimeMultiplayer.getWaitingRoomIntent(mGoogleApiClient, room,Integer.MAX_VALUE); 
and use 2 as the last argument to show play now button when 2 players are connected . But it does not help either .

Thanks 
Hoping for response

**Comment by squinney** [comment]
I'm also seeing the problem where callbacks do not fire as players are added one at a time, only when max players is reached.  I tried saving the Room object that is returned in onRoomCreated and polling to see if the participants in that room change as players are added, but it does not update.  Anybody know a way to work around this issue and figure out when players are added one at a time?
