### ISSUE TITLE
Import of BaseGame creates an empty src folder

### ISSUE THREAD

**Issue by giwrgos88** [playgameservices/android-basic-samples#96]
Trying to import BaseGameUtils into eclipse but it doesn't include the java files. the src folder is empty. how i can fix it? thanks

I went using this tutorial to import the BaseGame Utils
https://github.com/playgameservices/android-basic-samples﻿
![screen shot 2014-08-10 at 20 58 36](https://cloud.githubusercontent.com/assets/3164113/3870387/86063012-20cb-11e4-9add-fde1a5db5eca.png)

**Comment by vipulbehl** [comment]
Hi, I am unable to run this script but it gives me an error "this script must be run from the base directory of your working copy". I have gone through many questions on stackoverflow but couldn't find an answer. No matter where I place this folder i get the same error. Can you help me with this?

**Comment by claywilkinson** [comment]
if you clone this repository, it creates a directory named android-basic-samples.  Open a terminal window in that directory.  Then run `Scripts\make_eclipse_compat`.

**Comment by vipulbehl** [comment]
@claywilkinson it worked, Thank you.
